<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5" body_secondary_ratio="0.5">
	<global_window_position top="50" left="50" height="500" width="700"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="leo.20151212173315.1"><vh>@settings</vh>
<v t="leo.20151212173315.2"><vh>@data qt-gui-plugin-style-sheet</vh></v>
<v t="leo.20151212173315.3"><vh>@string initial_split_orientation = horizontal</vh></v>
</v>
<v t="amd.20160921213353.1"><vh>2016fall 簡報與網誌樣板系統</vh></v>
<v t="amd.20160106095324.1" a="E"><vh>@path ./../</vh>
<v t="leo.20151213173830.1" a="E"><vh>假如要在近端檢視, 使用下列按鈕</vh>
<v t="leo.20151213085727.1"><vh>@button pelican-blog</vh></v>
</v>
<v t="amd.20151215180106.1"><vh>設定與開發</vh>
<v t="amd.20151216151325.1" a="E"><vh>@clean index.html</vh>
<v t="amd.20161004083800.1" a="E"><vh>html</vh>
<v t="amd.20161004083800.2"><vh>head</vh></v>
<v t="amd.20161004083800.5" a="E"><vh>body</vh>
<v t="amd.20161004083800.6" a="E"><vh>reveal div</vh>
<v t="amd.20161004083800.7" a="E"><vh>slides div</vh>
<v t="amd.20161004095719.1" a="E"><vh>封面投影片</vh>
<v t="amd.20161004095719.2"><vh>封面投影片內容</vh></v>
</v>
<v t="yen.20161016023122.1" a="E"><vh>快捷鍵</vh>
<v t="yen.20161016023122.2"><vh>投影片快捷鍵</vh></v>
</v>
<v t="amd.20161004104820.1"><vh>三大主題教學</vh>
<v t="amd.20161004104641.1" a="E"><vh>主題教學</vh>
<v t="amd.20161004104641.2"><vh>計算機程式在教什麼?</vh></v>
</v>
<v t="yen.20161011155543.1" a="E"><vh>主題教學內容</vh>
<v t="yen.20161011155543.2"><vh>計算機程式在教什麼?</vh></v>
</v>
<v t="yen.20161011115740.1" a="E"><vh>相關課程</vh>
<v t="yen.20161011115740.2"><vh>計算機程式系列課程</vh></v>
</v>
<v t="amd.20161004105131.1" a="E"><vh>創造力</vh>
<v t="amd.20161004105131.2"><vh>何謂創造力?</vh></v>
</v>
<v t="yen.20161011114704.1" a="E"><vh>創造力</vh>
<v t="yen.20161011114704.2"><vh>何謂創造力?</vh></v>
</v>
<v t="yen.20161011121637.1"><vh>所謂自學</vh>
<v t="yen.20161011121637.2"><vh>自學的訓練</vh></v>
</v>
<v t="amd.20161004105716.1"><vh>執行力</vh>
<v t="amd.20161004105716.2"><vh>高效執行力</vh></v>
</v>
</v>
<v t="yen.20161016004633.1"><vh>CP 課程倉儲</vh>
<v t="yen.20161016004633.4"><vh>課程時段與規劃</vh>
<v t="yen.20161016004633.5"><vh>規劃、Wiki 與網誌</vh></v>
</v>
<v t="yen.20161016010643.1"><vh>下載 miniconda 可攜環境</vh>
<v t="yen.20161016010643.2"><vh>下載可攜程式環境</vh></v>
</v>
<v t="yen.20161016010719.1" a="E"><vh>學員自評項目</vh>
<v t="yen.20161016012922.1"><vh>下載可攜程式環境</vh></v>
</v>
</v>
<v t="yen.20161011122932.1"><vh>自學力訓練</vh>
<v t="yen.20161011122601.1" a="E"><vh>自學的材料</vh>
<v t="yen.20161011122601.2"><vh>自學 Python3</vh></v>
</v>
<v t="yen.20161011122957.1" a="E"><vh>Python 執行環境</vh>
<v t="yen.20161011122957.2"><vh>在哪裡執行?</vh></v>
</v>
<v t="yen.20161011123951.1" a="E"><vh>Python 解譯器</vh>
<v t="yen.20161011123951.2"><vh>Python 解譯器</vh></v>
</v>
<v t="yen.20161011124118.1" a="E"><vh>Python 版次</vh>
<v t="yen.20161011124118.2"><vh>Python 2 或 3?</vh></v>
</v>
</v>
<v t="yen.20161011125115.1"><vh>執行力訓練</vh>
<v t="yen.20161016011920.1" a="E"><vh>程式練習主題</vh>
<v t="yen.20161016011920.2"><vh>程式專題</vh></v>
</v>
<v t="yen.20161011125115.2" a="E"><vh>如何進行上課分組與排座位</vh>
<v t="yen.20161011125115.3"><vh>課程分組排座位</vh></v>
</v>
<v t="yen.20161016012215.1" a="E"><vh>如何寫一個猜數字遊戲?</vh>
<v t="yen.20161016012215.2"><vh>猜數字遊戲</vh></v>
</v>
<v t="yen.20161016012253.1" a="E"><vh>如何繪製 2D 靜態圖?</vh>
<v t="yen.20161016012253.2"><vh>2D 繪圖</vh></v>
</v>
<v t="yen.20161016012402.1" a="E"><vh>如何製作一個簡單的網際遊戲?</vh>
<v t="yen.20161016012402.2"><vh>網際遊戲</vh></v>
</v>
</v>
<v t="yen.20161011143808.1"><vh>協同力訓練</vh>
<v t="yen.20161011143808.2" a="E"><vh>Github 帳號</vh>
<v t="yen.20161011143808.3"><vh>Github 倉儲網頁</vh></v>
</v>
<v t="yen.20161011144113.1"><vh>倉儲子模組串連</vh>
<v t="yen.20161011144113.2"><vh>學員作業網頁定版</vh></v>
</v>
<v t="yen.20161011144715.1"><vh>倉儲版本拉回請求</vh>
<v t="yen.20161011144715.2"><vh>Github 倉儲拉回請求</vh></v>
</v>
</v>
<v t="yen.20161011145156.1"><vh>開始學 Python</vh>
<v t="yen.20161011145156.2" a="E"><vh>Python 基本語法</vh>
<v t="yen.20161011145156.3"><vh>Python3 語法</vh></v>
</v>
<v t="yen.20161011145156.4" a="E"><vh>Python 迴圈</vh>
<v t="yen.20161011145156.5"><vh>for 迴圈用法</vh></v>
</v>
<v t="yen.20161011145156.6"><vh>Python 函式</vh>
<v t="yen.20161011145156.7"><vh>函式用法</vh></v>
</v>
<v t="yen.20161011145755.1"><vh>Python 數列</vh>
<v t="yen.20161011145755.2"><vh>數列用法</vh></v>
</v>
<v t="yen.20161011145952.1"><vh>分組程式</vh>
<v t="yen.20161011145952.2"><vh>分組程式內容</vh></v>
</v>
<v t="yen.20161011150316.1"><vh>猜數字遊戲</vh>
<v t="yen.20161011150316.2"><vh>遊戲邏輯</vh></v>
</v>
<v t="yen.20161011150126.1"><vh>2 D 繪圖</vh>
<v t="yen.20161011150126.2"><vh>Python 網際繪圖</vh></v>
</v>
<v t="yen.20161011150901.1"><vh>2 D 動畫</vh>
<v t="yen.20161011150901.2"><vh>網際動畫範例</vh></v>
</v>
</v>
<v t="yen.20161016012809.1"><vh>各式內容引用範例</vh>
<v t="yen.20161016012809.2" a="E"><vh>導入數學符號與方程式</vh>
<v t="yen.20161016012809.3"><vh>LaTeX 格式方程式</vh></v>
</v>
<v t="yen.20161016012809.4" a="E"><vh>導入縮排程式碼</vh>
<v t="yen.20161016012809.5"><vh>引用程式碼</vh></v>
</v>
<v t="yen.20161016012809.6" a="E"><vh>導入影片</vh>
<v t="yen.20161016012809.7"><vh>iframe 導入影片</vh></v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
<v t="leo.20151213230723.1"><vh>Pelican 設定</vh>
<v t="leo.20151213230957.1"><vh>文章 Date 設定</vh></v>
<v t="leo.20151213230729.1"><vh>使用 summary plugin</vh></v>
</v>
<v t="amd.20151215170117.1"><vh>以下 pelicanconf.py 為近端與遠端的共同設定</vh></v>
<v t="leo.20151212173725.1"><vh>@edit pelicanconf.py</vh></v>
<v t="amd.20151215170221.1"><vh>以下 local_publishconf.py 為近端所使用的設定</vh></v>
<v t="leo.20151213085752.1"><vh>@edit local_publishconf.py</vh></v>
</v>
</v>
<v t="amd.20151215170350.1"><vh>以下為 content 目錄中的 md 檔案</vh></v>
<v t="amd.20151216001126.1"><vh>md 檔案範例</vh></v>
<v t="amd.20151215170031.1" a="E"><vh>@path ./../content</vh>
<v t="amd.20160106093454.1" a="E"><vh>yen 所寫的網誌文章</vh>
<v t="amd.20160727114506.1" a="E"><vh>201609</vh>
<v t="amd.20160727120222.1"><vh>@edit 20160921.md</vh></v>
<v t="leo.20161115230418.1"><vh>@edit 20161115.md</vh></v>
<v t="leo.20161118152432.1"><vh>@auto 20161118.md</vh></v>
<v t="leo.20161014142409.1"><vh>@edit 20161014.md</vh></v>
</v>
</v>
</v>
<v t="amd.20160106094754.1"><vh>@path ./../content/pages</vh>
<v t="amd.20160106094829.1" a="E"><vh>yen 所寫的 pages 文章</vh>
<v t="amd.20160106094844.1"><vh>@edit pages_1.md</vh></v>
</v>
</v>
<v t="amd.20161004202833.1"><vh>@edit ../README.md</vh></v>
<v t="yen.20161022111056.1"><vh>@button https server</vh></v>
<v t="yen.20161022151749.1"><vh>產生 .key 與 .crt</vh></v>
<v t="leo.20161115230332.2" a="E"><vh>Recovered Nodes</vh>
<v t="leo.20161115230332.3"><vh>Recovered node "head" from @clean index.html</vh>
<v t="leo.20161115230332.4"><vh>old:head</vh></v>
<v t="leo.20161115230332.5"><vh>new:head</vh></v>
</v>
<v t="leo.20161115230332.6"><vh>Recovered node "body" from @clean index.html</vh>
<v t="leo.20161115230332.7"><vh>old:body</vh></v>
<v t="leo.20161115230332.8"><vh>new:body</vh></v>
</v>
<v t="leo.20161115230332.9"><vh>Recovered node "封面投影片" from @clean index.html</vh>
<v t="leo.20161115230332.10"><vh>old:封面投影片</vh></v>
<v t="leo.20161115230332.11"><vh>new:封面投影片</vh></v>
</v>
<v t="leo.20161115230332.12"><vh>Recovered node "封面投影片內容" from @clean index.html</vh>
<v t="leo.20161115230332.13"><vh>old:封面投影片內容</vh></v>
<v t="leo.20161115230332.14"><vh>new:封面投影片內容</vh></v>
</v>
<v t="leo.20161115230332.15"><vh>Recovered node "快捷鍵" from @clean index.html</vh>
<v t="leo.20161115230332.16"><vh>old:快捷鍵</vh></v>
<v t="leo.20161115230332.17"><vh>new:快捷鍵</vh></v>
</v>
<v t="leo.20161115230332.18"><vh>Recovered node "投影片快捷鍵" from @clean index.html</vh>
<v t="leo.20161115230332.19"><vh>old:投影片快捷鍵</vh></v>
<v t="leo.20161115230332.20"><vh>new:投影片快捷鍵</vh></v>
</v>
<v t="leo.20161115230332.21"><vh>Recovered node "三大主題教學" from @clean index.html</vh>
<v t="leo.20161115230332.22"><vh>old:三大主題教學</vh></v>
<v t="leo.20161115230332.23"><vh>new:三大主題教學</vh></v>
</v>
<v t="leo.20161115230332.24"><vh>Recovered node "主題教學" from @clean index.html</vh>
<v t="leo.20161115230332.25"><vh>old:主題教學</vh></v>
<v t="leo.20161115230332.26"><vh>new:主題教學</vh></v>
</v>
<v t="leo.20161115230332.27"><vh>Recovered node "計算機程式在教什麼?" from @clean index.html</vh>
<v t="leo.20161115230332.28"><vh>old:計算機程式在教什麼?</vh></v>
<v t="leo.20161115230332.29"><vh>new:計算機程式在教什麼?</vh></v>
</v>
<v t="leo.20161115230332.30"><vh>Recovered node "主題教學內容" from @clean index.html</vh>
<v t="leo.20161115230332.31"><vh>old:主題教學內容</vh></v>
<v t="leo.20161115230332.32"><vh>new:主題教學內容</vh></v>
</v>
<v t="leo.20161115230332.33"><vh>Recovered node "計算機程式在教什麼?" from @clean index.html</vh>
<v t="leo.20161115230332.34"><vh>old:計算機程式在教什麼?</vh></v>
<v t="leo.20161115230332.35"><vh>new:計算機程式在教什麼?</vh></v>
</v>
<v t="leo.20161115230332.36"><vh>Recovered node "相關課程" from @clean index.html</vh>
<v t="leo.20161115230332.37"><vh>old:相關課程</vh></v>
<v t="leo.20161115230332.38"><vh>new:相關課程</vh></v>
</v>
<v t="leo.20161115230332.39"><vh>Recovered node "計算機程式系列課程" from @clean index.html</vh>
<v t="leo.20161115230332.40"><vh>old:計算機程式系列課程</vh></v>
<v t="leo.20161115230332.41"><vh>new:計算機程式系列課程</vh></v>
</v>
<v t="leo.20161115230332.42"><vh>Recovered node "創造力" from @clean index.html</vh>
<v t="leo.20161115230332.43"><vh>old:創造力</vh></v>
<v t="leo.20161115230332.44"><vh>new:創造力</vh></v>
</v>
<v t="leo.20161115230332.45"><vh>Recovered node "何謂創造力?" from @clean index.html</vh>
<v t="leo.20161115230332.46"><vh>old:何謂創造力?</vh></v>
<v t="leo.20161115230332.47"><vh>new:何謂創造力?</vh></v>
</v>
<v t="leo.20161115230332.48"><vh>Recovered node "創造力" from @clean index.html</vh>
<v t="leo.20161115230332.49"><vh>old:創造力</vh></v>
<v t="leo.20161115230332.50"><vh>new:創造力</vh></v>
</v>
<v t="leo.20161115230332.51"><vh>Recovered node "何謂創造力?" from @clean index.html</vh>
<v t="leo.20161115230332.52"><vh>old:何謂創造力?</vh></v>
<v t="leo.20161115230332.53"><vh>new:何謂創造力?</vh></v>
</v>
<v t="leo.20161115230332.54"><vh>Recovered node "所謂自學" from @clean index.html</vh>
<v t="leo.20161115230332.55"><vh>old:所謂自學</vh></v>
<v t="leo.20161115230332.56"><vh>new:所謂自學</vh></v>
</v>
<v t="leo.20161115230332.57"><vh>Recovered node "自學的訓練" from @clean index.html</vh>
<v t="leo.20161115230332.58"><vh>old:自學的訓練</vh></v>
<v t="leo.20161115230332.59"><vh>new:自學的訓練</vh></v>
</v>
<v t="leo.20161115230332.60"><vh>Recovered node "執行力" from @clean index.html</vh>
<v t="leo.20161115230332.61"><vh>old:執行力</vh></v>
<v t="leo.20161115230332.62"><vh>new:執行力</vh></v>
</v>
<v t="leo.20161115230332.63"><vh>Recovered node "高效執行力" from @clean index.html</vh>
<v t="leo.20161115230332.64"><vh>old:高效執行力</vh></v>
<v t="leo.20161115230332.65"><vh>new:高效執行力</vh></v>
</v>
<v t="leo.20161115230332.66"><vh>Recovered node "CP 課程倉儲" from @clean index.html</vh>
<v t="leo.20161115230332.67"><vh>old:CP 課程倉儲</vh></v>
<v t="leo.20161115230332.68"><vh>new:CP 課程倉儲</vh></v>
</v>
<v t="leo.20161115230332.69"><vh>Recovered node "課程時段與規劃" from @clean index.html</vh>
<v t="leo.20161115230332.70"><vh>old:課程時段與規劃</vh></v>
<v t="leo.20161115230332.71"><vh>new:課程時段與規劃</vh></v>
</v>
<v t="leo.20161115230332.72"><vh>Recovered node "規劃、Wiki 與網誌" from @clean index.html</vh>
<v t="leo.20161115230332.73"><vh>old:規劃、Wiki 與網誌</vh></v>
<v t="leo.20161115230332.74"><vh>new:規劃、Wiki 與網誌</vh></v>
</v>
<v t="leo.20161115230332.75"><vh>Recovered node "下載 miniconda 可攜環境" from @clean index.html</vh>
<v t="leo.20161115230332.76"><vh>old:下載 miniconda 可攜環境</vh></v>
<v t="leo.20161115230332.77"><vh>new:下載 miniconda 可攜環境</vh></v>
</v>
<v t="leo.20161115230332.78"><vh>Recovered node "下載可攜程式環境" from @clean index.html</vh>
<v t="leo.20161115230332.79"><vh>old:下載可攜程式環境</vh></v>
<v t="leo.20161115230332.80"><vh>new:下載可攜程式環境</vh></v>
</v>
<v t="leo.20161115230332.81"><vh>Recovered node "學員自評項目" from @clean index.html</vh>
<v t="leo.20161115230332.82"><vh>old:學員自評項目</vh></v>
<v t="leo.20161115230332.83"><vh>new:學員自評項目</vh></v>
</v>
<v t="leo.20161115230332.84"><vh>Recovered node "下載可攜程式環境" from @clean index.html</vh>
<v t="leo.20161115230332.85"><vh>old:下載可攜程式環境</vh></v>
<v t="leo.20161115230332.86"><vh>new:下載可攜程式環境</vh></v>
</v>
<v t="leo.20161115230332.87"><vh>Recovered node "自學力訓練" from @clean index.html</vh>
<v t="leo.20161115230332.88"><vh>old:自學力訓練</vh></v>
<v t="leo.20161115230332.89"><vh>new:自學力訓練</vh></v>
</v>
<v t="leo.20161115230332.90"><vh>Recovered node "自學的材料" from @clean index.html</vh>
<v t="leo.20161115230332.91"><vh>old:自學的材料</vh></v>
<v t="leo.20161115230332.92"><vh>new:自學的材料</vh></v>
</v>
<v t="leo.20161115230332.93"><vh>Recovered node "自學 Python3" from @clean index.html</vh>
<v t="leo.20161115230332.94"><vh>old:自學 Python3</vh></v>
<v t="leo.20161115230332.95"><vh>new:自學 Python3</vh></v>
</v>
<v t="leo.20161115230332.96"><vh>Recovered node "Python 執行環境" from @clean index.html</vh>
<v t="leo.20161115230332.97"><vh>old:Python 執行環境</vh></v>
<v t="leo.20161115230332.98"><vh>new:Python 執行環境</vh></v>
</v>
<v t="leo.20161115230332.99"><vh>Recovered node "在哪裡執行?" from @clean index.html</vh>
<v t="leo.20161115230332.100"><vh>old:在哪裡執行?</vh></v>
<v t="leo.20161115230332.101"><vh>new:在哪裡執行?</vh></v>
</v>
<v t="leo.20161115230332.102"><vh>Recovered node "Python 解譯器" from @clean index.html</vh>
<v t="leo.20161115230332.103"><vh>old:Python 解譯器</vh></v>
<v t="leo.20161115230332.104"><vh>new:Python 解譯器</vh></v>
</v>
<v t="leo.20161115230332.105"><vh>Recovered node "Python 解譯器" from @clean index.html</vh>
<v t="leo.20161115230332.106"><vh>old:Python 解譯器</vh></v>
<v t="leo.20161115230332.107"><vh>new:Python 解譯器</vh></v>
</v>
<v t="leo.20161115230332.108"><vh>Recovered node "Python 版次" from @clean index.html</vh>
<v t="leo.20161115230332.109"><vh>old:Python 版次</vh></v>
<v t="leo.20161115230332.110"><vh>new:Python 版次</vh></v>
</v>
<v t="leo.20161115230332.111"><vh>Recovered node "Python 2 或 3?" from @clean index.html</vh>
<v t="leo.20161115230332.112"><vh>old:Python 2 或 3?</vh></v>
<v t="leo.20161115230332.113"><vh>new:Python 2 或 3?</vh></v>
</v>
<v t="leo.20161115230332.114"><vh>Recovered node "執行力訓練" from @clean index.html</vh>
<v t="leo.20161115230332.115"><vh>old:執行力訓練</vh></v>
<v t="leo.20161115230332.116"><vh>new:執行力訓練</vh></v>
</v>
<v t="leo.20161115230332.117"><vh>Recovered node "程式練習主題" from @clean index.html</vh>
<v t="leo.20161115230332.118"><vh>old:程式練習主題</vh></v>
<v t="leo.20161115230332.119"><vh>new:程式練習主題</vh></v>
</v>
<v t="leo.20161115230332.120"><vh>Recovered node "程式專題" from @clean index.html</vh>
<v t="leo.20161115230332.121"><vh>old:程式專題</vh></v>
<v t="leo.20161115230332.122"><vh>new:程式專題</vh></v>
</v>
<v t="leo.20161115230332.123"><vh>Recovered node "如何進行上課分組與排座位" from @clean index.html</vh>
<v t="leo.20161115230332.124"><vh>old:如何進行上課分組與排座位</vh></v>
<v t="leo.20161115230332.125"><vh>new:如何進行上課分組與排座位</vh></v>
</v>
<v t="leo.20161115230332.126"><vh>Recovered node "課程分組排座位" from @clean index.html</vh>
<v t="leo.20161115230332.127"><vh>old:課程分組排座位</vh></v>
<v t="leo.20161115230332.128"><vh>new:課程分組排座位</vh></v>
</v>
<v t="leo.20161115230332.129"><vh>Recovered node "如何寫一個猜數字遊戲?" from @clean index.html</vh>
<v t="leo.20161115230332.130"><vh>old:如何寫一個猜數字遊戲?</vh></v>
<v t="leo.20161115230332.131"><vh>new:如何寫一個猜數字遊戲?</vh></v>
</v>
<v t="leo.20161115230332.132"><vh>Recovered node "猜數字遊戲" from @clean index.html</vh>
<v t="leo.20161115230332.133"><vh>old:猜數字遊戲</vh></v>
<v t="leo.20161115230332.134"><vh>new:猜數字遊戲</vh></v>
</v>
<v t="leo.20161115230332.135"><vh>Recovered node "如何繪製 2D 靜態圖?" from @clean index.html</vh>
<v t="leo.20161115230332.136"><vh>old:如何繪製 2D 靜態圖?</vh></v>
<v t="leo.20161115230332.137"><vh>new:如何繪製 2D 靜態圖?</vh></v>
</v>
<v t="leo.20161115230332.138"><vh>Recovered node "2D 繪圖" from @clean index.html</vh>
<v t="leo.20161115230332.139"><vh>old:2D 繪圖</vh></v>
<v t="leo.20161115230332.140"><vh>new:2D 繪圖</vh></v>
</v>
<v t="leo.20161115230332.141"><vh>Recovered node "如何製作一個簡單的網際遊戲?" from @clean index.html</vh>
<v t="leo.20161115230332.142"><vh>old:如何製作一個簡單的網際遊戲?</vh></v>
<v t="leo.20161115230332.143"><vh>new:如何製作一個簡單的網際遊戲?</vh></v>
</v>
<v t="leo.20161115230332.144"><vh>Recovered node "網際遊戲" from @clean index.html</vh>
<v t="leo.20161115230332.145"><vh>old:網際遊戲</vh></v>
<v t="leo.20161115230332.146"><vh>new:網際遊戲</vh></v>
</v>
<v t="leo.20161115230332.147"><vh>Recovered node "協同力訓練" from @clean index.html</vh>
<v t="leo.20161115230332.148"><vh>old:協同力訓練</vh></v>
<v t="leo.20161115230332.149"><vh>new:協同力訓練</vh></v>
</v>
<v t="leo.20161115230332.150"><vh>Recovered node "Github 帳號" from @clean index.html</vh>
<v t="leo.20161115230332.151"><vh>old:Github 帳號</vh></v>
<v t="leo.20161115230332.152"><vh>new:Github 帳號</vh></v>
</v>
<v t="leo.20161115230332.153"><vh>Recovered node "Github 倉儲網頁" from @clean index.html</vh>
<v t="leo.20161115230332.154"><vh>old:Github 倉儲網頁</vh></v>
<v t="leo.20161115230332.155"><vh>new:Github 倉儲網頁</vh></v>
</v>
<v t="leo.20161115230332.156"><vh>Recovered node "倉儲子模組串連" from @clean index.html</vh>
<v t="leo.20161115230332.157"><vh>old:倉儲子模組串連</vh></v>
<v t="leo.20161115230332.158"><vh>new:倉儲子模組串連</vh></v>
</v>
<v t="leo.20161115230332.159"><vh>Recovered node "學員作業網頁定版" from @clean index.html</vh>
<v t="leo.20161115230332.160"><vh>old:學員作業網頁定版</vh></v>
<v t="leo.20161115230332.161"><vh>new:學員作業網頁定版</vh></v>
</v>
<v t="leo.20161115230332.162"><vh>Recovered node "倉儲版本拉回請求" from @clean index.html</vh>
<v t="leo.20161115230332.163"><vh>old:倉儲版本拉回請求</vh></v>
<v t="leo.20161115230332.164"><vh>new:倉儲版本拉回請求</vh></v>
</v>
<v t="leo.20161115230332.165"><vh>Recovered node "Github 倉儲拉回請求" from @clean index.html</vh>
<v t="leo.20161115230332.166"><vh>old:Github 倉儲拉回請求</vh></v>
<v t="leo.20161115230332.167"><vh>new:Github 倉儲拉回請求</vh></v>
</v>
<v t="leo.20161115230332.168"><vh>Recovered node "開始學 Python" from @clean index.html</vh>
<v t="leo.20161115230332.169"><vh>old:開始學 Python</vh></v>
<v t="leo.20161115230332.170"><vh>new:開始學 Python</vh></v>
</v>
<v t="leo.20161115230332.171"><vh>Recovered node "Python 基本語法" from @clean index.html</vh>
<v t="leo.20161115230332.172"><vh>old:Python 基本語法</vh></v>
<v t="leo.20161115230332.173"><vh>new:Python 基本語法</vh></v>
</v>
<v t="leo.20161115230332.174"><vh>Recovered node "Python3 語法" from @clean index.html</vh>
<v t="leo.20161115230332.175"><vh>old:Python3 語法</vh></v>
<v t="leo.20161115230332.176"><vh>new:Python3 語法</vh></v>
</v>
<v t="leo.20161115230332.177"><vh>Recovered node "Python 迴圈" from @clean index.html</vh>
<v t="leo.20161115230332.178"><vh>old:Python 迴圈</vh></v>
<v t="leo.20161115230332.179"><vh>new:Python 迴圈</vh></v>
</v>
<v t="leo.20161115230332.180"><vh>Recovered node "for 迴圈用法" from @clean index.html</vh>
<v t="leo.20161115230332.181"><vh>old:for 迴圈用法</vh></v>
<v t="leo.20161115230332.182"><vh>new:for 迴圈用法</vh></v>
</v>
<v t="leo.20161115230332.183"><vh>Recovered node "Python 函式" from @clean index.html</vh>
<v t="leo.20161115230332.184"><vh>old:Python 函式</vh></v>
<v t="leo.20161115230332.185"><vh>new:Python 函式</vh></v>
</v>
<v t="leo.20161115230332.186"><vh>Recovered node "函式用法" from @clean index.html</vh>
<v t="leo.20161115230332.187"><vh>old:函式用法</vh></v>
<v t="leo.20161115230332.188"><vh>new:函式用法</vh></v>
</v>
<v t="leo.20161115230332.189"><vh>Recovered node "Python 數列" from @clean index.html</vh>
<v t="leo.20161115230332.190"><vh>old:Python 數列</vh></v>
<v t="leo.20161115230332.191"><vh>new:Python 數列</vh></v>
</v>
<v t="leo.20161115230332.192"><vh>Recovered node "數列用法" from @clean index.html</vh>
<v t="leo.20161115230332.193"><vh>old:數列用法</vh></v>
<v t="leo.20161115230332.194"><vh>new:數列用法</vh></v>
</v>
<v t="leo.20161115230332.195"><vh>Recovered node "分組程式" from @clean index.html</vh>
<v t="leo.20161115230332.196"><vh>old:分組程式</vh></v>
<v t="leo.20161115230332.197"><vh>new:分組程式</vh></v>
</v>
<v t="leo.20161115230332.198"><vh>Recovered node "分組程式內容" from @clean index.html</vh>
<v t="leo.20161115230332.199"><vh>old:分組程式內容</vh></v>
<v t="leo.20161115230332.200"><vh>new:分組程式內容</vh></v>
</v>
<v t="leo.20161115230332.201"><vh>Recovered node "猜數字遊戲" from @clean index.html</vh>
<v t="leo.20161115230332.202"><vh>old:猜數字遊戲</vh></v>
<v t="leo.20161115230332.203"><vh>new:猜數字遊戲</vh></v>
</v>
<v t="leo.20161115230332.204"><vh>Recovered node "遊戲邏輯" from @clean index.html</vh>
<v t="leo.20161115230332.205"><vh>old:遊戲邏輯</vh></v>
<v t="leo.20161115230332.206"><vh>new:遊戲邏輯</vh></v>
</v>
<v t="leo.20161115230332.207"><vh>Recovered node "2 D 繪圖" from @clean index.html</vh>
<v t="leo.20161115230332.208"><vh>old:2 D 繪圖</vh></v>
<v t="leo.20161115230332.209"><vh>new:2 D 繪圖</vh></v>
</v>
<v t="leo.20161115230332.210"><vh>Recovered node "Python 網際繪圖" from @clean index.html</vh>
<v t="leo.20161115230332.211"><vh>old:Python 網際繪圖</vh></v>
<v t="leo.20161115230332.212"><vh>new:Python 網際繪圖</vh></v>
</v>
<v t="leo.20161115230332.213"><vh>Recovered node "2 D 動畫" from @clean index.html</vh>
<v t="leo.20161115230332.214"><vh>old:2 D 動畫</vh></v>
<v t="leo.20161115230332.215"><vh>new:2 D 動畫</vh></v>
</v>
<v t="leo.20161115230332.216"><vh>Recovered node "網際動畫範例" from @clean index.html</vh>
<v t="leo.20161115230332.217"><vh>old:網際動畫範例</vh></v>
<v t="leo.20161115230332.218"><vh>new:網際動畫範例</vh></v>
</v>
<v t="leo.20161115230332.219"><vh>Recovered node "各式內容引用範例" from @clean index.html</vh>
<v t="leo.20161115230332.220"><vh>old:各式內容引用範例</vh></v>
<v t="leo.20161115230332.221"><vh>new:各式內容引用範例</vh></v>
</v>
<v t="leo.20161115230332.222"><vh>Recovered node "導入數學符號與方程式" from @clean index.html</vh>
<v t="leo.20161115230332.223"><vh>old:導入數學符號與方程式</vh></v>
<v t="leo.20161115230332.224"><vh>new:導入數學符號與方程式</vh></v>
</v>
<v t="leo.20161115230332.225"><vh>Recovered node "LaTeX 格式方程式" from @clean index.html</vh>
<v t="leo.20161115230332.226"><vh>old:LaTeX 格式方程式</vh></v>
<v t="leo.20161115230332.227"><vh>new:LaTeX 格式方程式</vh></v>
</v>
<v t="leo.20161115230332.228"><vh>Recovered node "導入影片" from @clean index.html</vh>
<v t="leo.20161115230332.229"><vh>old:導入影片</vh></v>
<v t="leo.20161115230332.230"><vh>new:導入影片</vh></v>
</v>
<v t="leo.20161115230332.231"><vh>Recovered node "iframe 導入影片" from @clean index.html</vh>
<v t="leo.20161115230332.232"><vh>old:iframe 導入影片</vh></v>
<v t="leo.20161115230332.233"><vh>new:iframe 導入影片</vh></v>
</v>
</v>
<v t="leo.20161118133515.2" a="E"><vh>Recovered Nodes</vh>
<v t="leo.20161118133515.3"><vh>Recovered node "封面投影片" from @clean index.html</vh>
<v t="leo.20161118133515.4"><vh>old:封面投影片</vh></v>
<v t="leo.20161118133515.5"><vh>new:封面投影片</vh></v>
</v>
<v t="leo.20161118133515.6"><vh>Recovered node "封面投影片內容" from @clean index.html</vh>
<v t="leo.20161118133515.7"><vh>old:封面投影片內容</vh></v>
<v t="leo.20161118133515.8"><vh>new:封面投影片內容</vh></v>
</v>
<v t="leo.20161118133515.9"><vh>Recovered node "創造力" from @clean index.html</vh>
<v t="leo.20161118133515.10"><vh>old:創造力</vh></v>
<v t="leo.20161118133515.11"><vh>new:創造力</vh></v>
</v>
<v t="leo.20161118133515.12"><vh>Recovered node "何謂創造力?" from @clean index.html</vh>
<v t="leo.20161118133515.13"><vh>old:何謂創造力?</vh></v>
<v t="leo.20161118133515.14"><vh>new:何謂創造力?</vh></v>
</v>
</v>
</vnodes>
<tnodes>
<t tx="amd.20151215170031.1"></t>
<t tx="amd.20151215170117.1"></t>
<t tx="amd.20151215170221.1"></t>
<t tx="amd.20151215170350.1"></t>
<t tx="amd.20151215180106.1"></t>
<t tx="amd.20151216001126.1">@language md
Title: 文章標題 (請注意各文章的標題不可相同, 比較保險的作法是冠上四個學號尾碼)
Date: 2016-09-2 12:00
Category: 類別
Tags: 標籤
Author: yen

這裡放入文章摘要

&lt;!-- PELICAN_END_SUMMARY --&gt;

這裡為文章主要內容

程式碼

&lt;pre class="brush: python;"&gt;
print("hello")
&lt;/pre&gt;</t>
<t tx="amd.20151216151325.1">@language xml
@tabwidth -4
@others
</t>
<t tx="amd.20160106093454.1"></t>
<t tx="amd.20160106094754.1"></t>
<t tx="amd.20160106094829.1"></t>
<t tx="amd.20160106095324.1"></t>
<t tx="amd.20160727114506.1"></t>
<t tx="amd.20160921213353.1"></t>
<t tx="amd.20161004083800.1">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
@others
&lt;/html&gt;
</t>
<t tx="amd.20161004083800.2">&lt;head&gt;
    &lt;meta charset="utf-8"&gt;
    &lt;title&gt;   s40523146 謝秉軒  WELCOME
&lt;/title&gt;
    &lt;meta name="description" content="A framework for easily creating beautiful presentations using HTML"&gt;
    &lt;meta name="author" content="Hakim El Hattab"&gt;
    
    &lt;meta name="apple-mobile-web-app-capable" content="yes"&gt;
    &lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"&gt;
    
    &lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"&gt;
    
    &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/reveal.css"&gt;
    &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/theme/black.css" id="theme"&gt;
    
    &lt;!-- Theme used for syntax highlighting of code --&gt;
    &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/lib/css/zenburn.css"&gt;

    &lt;!-- Printing and PDF exports --&gt;
    &lt;script&gt;
        var link = document.createElement( 'link' );
        link.rel = 'stylesheet';
        link.type = 'text/css';
        link.href = window.location.search.match( /print-pdf/gi ) ? 'https://cad-lab.github.io/cadlab_data/reveal/css/print/pdf.css' : 'https://cad-lab.github.io/cadlab_data/reveal/css/print/paper.css';
        document.getElementsByTagName( 'head' )[0].appendChild( link );
    &lt;/script&gt;

    &lt;!--[if lt IE 9]&gt;
    &lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/html5shiv.js"&gt;&lt;/script&gt;
    &lt;![endif]--&gt;
&lt;/head&gt;

</t>
<t tx="amd.20161004083800.5">&lt;body&gt;
@others
&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/js/reveal.js"&gt;&lt;/script&gt;
&lt;script&gt;
        // More info https://github.com/hakimel/reveal.js#configuration
        Reveal.initialize({
            controls: true,
            progress: true,
            history: true,
            center: true,
            transition: 'slide', // none/fade/slide/convex/concave/zoom
            // More info https://github.com/hakimel/reveal.js#dependencies
            dependencies: [
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/lib/js/classList.js', condition: function() { return !document.body.classList; } },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/zoom-js/zoom.js', async: true },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/notes/notes.js', async: true },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/math/math.js', async: true }
            ]
        });
&lt;/script&gt;
&lt;/body&gt;
</t>
<t tx="amd.20161004083800.6">&lt;div class="reveal"&gt;
@others
&lt;/div&gt;

</t>
<t tx="amd.20161004083800.7">&lt;!-- Any section element inside of this container is displayed as a slide --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;

</t>
<t tx="amd.20161004095719.1">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;h1&gt;s40523146  謝秉軒  Welcome&lt;/h1&gt;
    &lt;p&gt;
    &lt;small&gt;
    Created by &lt;a href="https://github.com/s40523146"&gt;s40523146&lt;/a&gt;
    &lt;/small&gt;
</t>
<t tx="amd.20161004095719.2"># s40523146謝秉軒計算機課程

### THE HTML PRESENTATION FRAMEWORK

&lt;small&gt;
Created by s40523146
[s40523146](https://github.com/s40523146)
&lt;/small&gt;

[blog](blog/index.html)
    &lt;/script&gt;
&lt;/section&gt;


						
&lt;section&gt;
</t>
<t tx="amd.20161004104641.1">&lt;/section&gt;

@others
### 1. 自學能力 (CC1, Self-learning)
### 2. 程式能力 (CC2, Programming)
### 3. 想像能力 (CC3, Imagination)

    &lt;/script&gt;
</t>
<t tx="amd.20161004104641.2">
						
&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
# 強化創造能力

創造力至少包含三種元素:
</t>
<t tx="amd.20161004104820.1">    &lt;/script&gt;
@others
    &lt;/p&gt;
</t>
<t tx="amd.20161004105131.1">### 4. 執行協同專案 (CD4, Project)

@others
&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
## GIT CLONE

</t>
<t tx="amd.20161004105131.2">
    &lt;/script&gt;
&lt;/section&gt;


						
&lt;/section&gt;
</t>
<t tx="amd.20161004105716.1">    &lt;h2&gt;github_intro&lt;/h2&gt;
    &lt;iframe src="https://player.vimeo.com/video/183950627" width="640" height="492" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
@others
    &lt;iframe src="https://player.vimeo.com/video/183954581" width="640" height="492" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;p&gt;
    &lt;a href="https://vimeo.com/183954581"&gt;2016-09-23_fork_pull_requests&lt;/a&gt; from 
    &lt;a href="https://vimeo.com/user24079973"&gt;虎尾科大機械設計工程&lt;/a&gt; on 
    &lt;a href="https://vimeo.com"&gt;Vimeo&lt;/a&gt;.
</t>
<t tx="amd.20161004105716.2">    &lt;p&gt;
    &lt;a href="https://vimeo.com/183950627"&gt;2016-09-23_cpb_github_intro&lt;/a&gt; from 
    &lt;a href="https://vimeo.com/user24079973"&gt;虎尾科大機械設計工程&lt;/a&gt; on 
    &lt;a href="https://vimeo.com"&gt;Vimeo&lt;/a&gt;.
    &lt;/p&gt;
&lt;/section&gt;
&lt;section&gt;
    &lt;h2&gt;fork_pull_requests&lt;/h2&gt;
</t>
<t tx="leo.20151212173315.1"></t>
<t tx="leo.20151212173315.2">QTreeWidget {
    /* These apply to the selected item, but not to editing items.*/
    background-color: #ffffec; /* Leo's traditional tree color */
    selection-color: black; /* was white */
    selection-background-color: lightgrey;
    /* font-family: SansSerif; */
    /*font-family: DejaVu Sans Mono;*/
    font-family:YaHei Mono;
    /* 標題字型大小設定 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
 }

/* Headline edit widgets */
QTreeWidget QLineEdit {
    background-color: cornsilk;
    selection-color: white;
    selection-background-color: blue;
    /*font-family: DejaVu Sans Mono;*/    
    font-family:YaHei Mono;
    /* 沒有特別對應字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/* The log panes */
QTextEdit {
    background-color: #f2fdff;
    selection-color: red;
    selection-background-color: blue;
    /* font-family: Courier New; */
    font-family:YaHei Mono;
    /* log font 大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/* The body pane */
QTextEdit#richTextEdit {
    background-color: #fdf5f5; /* A kind of pink. */
    selection-color: white;
    selection-background-color: red;
    /*font-family: DejaVu Sans Mono;*/
    /* font-family: Courier New; */
    font-family:YaHei Mono;
    /* 內文字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

QLabel {
    font-family:YaHei Mono;'CherryPy', 'pytz', 'mako', 'beautifulsoup4', 'pymysql', 'peewee'
    /* 下方的 Minibuffer 標題字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

/* Editor labels */
QLineEdit#editorLabel {
    background-color: #ffffec;
    font-family:YaHei Mono;
    /* 沒有直接對應字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
    border: 2px;
    margin: 2px;
}</t>
<t tx="leo.20151212173315.3">horizontal: body pane to the left
vertical: body pane on the botton</t>
<t tx="leo.20151213085727.1">@language python
import os
#os.system("pelican content -o output -s local_publishconf.py -t theme/pelican-bootstrap3")
os.system("pelican content -o blog -s local_publishconf.py")
g.es("admin pelican 近端執行完畢")


</t>
<t tx="leo.20151213173830.1"></t>
<t tx="leo.20151213230723.1"></t>
<t tx="leo.20151213230729.1">利用

&lt;!-- PELICAN_END_SUMMARY --&gt;

來界定 Summary 摘要內容

前提, 必須設定 

PLUGIN_PATHS = ['plugin']

與

PLUGINS = ['liquid_tags.notebook', 'summary']

並且從 https://github.com/getpelican/pelican-plugins

取得 summary plugin</t>
<t tx="leo.20151213230957.1"># 設定網誌以 md 檔案建立的 file system date 為準, 無需自行設定

DEFAULT_DATE = 'fs'</t>
<t tx="leo.20161115230332.10">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161115230332.100"># 在哪裡執行?

### 單機操作系統中 (近端)
### 單機連結到遠端主機中 (遠端)
### 瀏覽器中 (網際端)
</t>
<t tx="leo.20161115230332.101"></t>
<t tx="leo.20161115230332.102">(uncached) yen.20161011123951.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161115230332.103">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161115230332.104">@others
</t>
<t tx="leo.20161115230332.105">(uncached) yen.20161011123951.2
Diff...
+ # Python 解譯器
+ 
+ CPython: https://www.python.org/
+ 
+ (Anaconda: https://www.continuum.io/downloads)
+     
+ IronPython (.NET): http://ironpython.net/
+ 
+ Jython (Java): http://www.jython.org/
+ 
+ Pypy (Python): http://pypy.org/
+ 
+ Brython (Javascript): https://www.brython.info/
</t>
<t tx="leo.20161115230332.106"># Python 解譯器

CPython: https://www.python.org/

(Anaconda: https://www.continuum.io/downloads)
    
IronPython (.NET): http://ironpython.net/

Jython (Java): http://www.jython.org/

Pypy (Python): http://pypy.org/

Brython (Javascript): https://www.brython.info/
</t>
<t tx="leo.20161115230332.107"></t>
<t tx="leo.20161115230332.108">(uncached) yen.20161011124118.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161115230332.109">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161115230332.11">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;h1&gt;s40523146  謝秉軒  Welcome&lt;/h1&gt;
    &lt;p&gt;
    &lt;small&gt;
    Created by &lt;a href="http://chiamingyen.github.io/kmolab/blog/tag/2016fallcp.html"&gt;s40523142&lt;/a&gt;
    &lt;/small&gt;
</t>
<t tx="leo.20161115230332.110">@others
</t>
<t tx="leo.20161115230332.111">(uncached) yen.20161011124118.2
Diff...
+ # Python 2 或 3?
+ 
+ ### 業界大部份仍以 2.7 版為主
+ 但是, 若沒有特別約束
+ ### 建議直接學習 Python3
</t>
<t tx="leo.20161115230332.112"># Python 2 或 3?

### 業界大部份仍以 2.7 版為主
但是, 若沒有特別約束
### 建議直接學習 Python3
</t>
<t tx="leo.20161115230332.113"></t>
<t tx="leo.20161115230332.114">(uncached) yen.20161011125115.1
Diff...
+ &lt;section&gt;
  @others
+ &lt;/section&gt;</t>
<t tx="leo.20161115230332.115">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20161115230332.116">@others
</t>
<t tx="leo.20161115230332.117">(uncached) yen.20161016011920.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161115230332.118">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161115230332.119">@others
</t>
<t tx="leo.20161115230332.12">(uncached) amd.20161004095719.2
Diff...
- # s40523146謝秉軒計算機課程
+ # 2016Fall 計算機程式課程
  
- ### THE HTML PRESENTATION FRAMEWORK
+ ### 虎科大機械設計工程系
  
  &lt;small&gt;
+ Created by [KMOLab](http://chiamingyen.github.io/kmolab/blog/)
- Created by [Hakim El Hattab](http://hakim.se)
- [@hakimel](http://twitter.com/hakimel)
  &lt;/small&gt;
  
+ [甲班計算機程式課程網誌](blog/index.html)
- [blog](blog/index.html)
-     &lt;/script&gt;
- &lt;/section&gt;
  
+ [乙班計算機程式課程網誌](https://mdecourse.github.io/2016fallcpb/blog)
  
- 						
- &lt;section&gt;
+ [計算機程式教學影片](https://vimeo.com/user24079973)
+ 
+ [電腦輔助設計室電腦硬體](http://project.mde.tw/blog/yen-dian-nao-fu-zhu-she-ji-shi-dian-nao-pei-zhi.html)
</t>
<t tx="leo.20161115230332.120">(uncached) yen.20161016011920.2
Diff...
+ # 計算機程式專題
+ 
+ * 如何進行上課分組與排座位?
+ * 如何寫一個猜數字遊戲?
+ * 如何繪製 2D 靜態圖?
+ * 如何製作一個簡單的網際遊戲?
</t>
<t tx="leo.20161115230332.121"># 計算機程式專題

* 如何進行上課分組與排座位?
* 如何寫一個猜數字遊戲?
* 如何繪製 2D 靜態圖?
* 如何製作一個簡單的網際遊戲?
</t>
<t tx="leo.20161115230332.122"></t>
<t tx="leo.20161115230332.123">(uncached) yen.20161011125115.2
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161115230332.124">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161115230332.125">@others
</t>
<t tx="leo.20161115230332.126">(uncached) yen.20161011125115.3
Diff...
+ # 課程分組排座位
+ 
+ * 想像一下分組流程
+ * 請畫出流程圖
+ * 如何進行最好?
</t>
<t tx="leo.20161115230332.127"># 課程分組排座位

* 想像一下分組流程
* 請畫出流程圖
* 如何進行最好?
</t>
<t tx="leo.20161115230332.128"></t>
<t tx="leo.20161115230332.129">(uncached) yen.20161016012215.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161115230332.13"># 2016Fall 計算機程式課程

### 虎科大機械設計工程系

&lt;small&gt;
Created by [KMOLab](http://chiamingyen.github.io/kmolab/blog/)
&lt;/small&gt;

[甲班計算機程式課程網誌](blog/index.html)

[乙班計算機程式課程網誌](https://mdecourse.github.io/2016fallcpb/blog)

[計算機程式教學影片](https://vimeo.com/user24079973)

[電腦輔助設計室電腦硬體](http://project.mde.tw/blog/yen-dian-nao-fu-zhu-she-ji-shi-dian-nao-pei-zhi.html)
</t>
<t tx="leo.20161115230332.130">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161115230332.131">@others
</t>
<t tx="leo.20161115230332.132">(uncached) yen.20161016012215.2
Diff...
+ # 猜數字遊戲
+ 
+ * 單機執行還是瀏覽器執行?
+ * 請畫出流程圖
+ * 有沒有參考資料?
</t>
<t tx="leo.20161115230332.133"># 猜數字遊戲

* 單機執行還是瀏覽器執行?
* 請畫出流程圖
* 有沒有參考資料?
</t>
<t tx="leo.20161115230332.134"></t>
<t tx="leo.20161115230332.135">(uncached) yen.20161016012253.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161115230332.136">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161115230332.137">@others
</t>
<t tx="leo.20161115230332.138">(uncached) yen.20161016012253.2
Diff...
+ # 2D 繪圖
+ 
+ * 單機執行還是瀏覽器執行?
+ * 請畫出流程圖
+ * 有沒有參考資料?
</t>
<t tx="leo.20161115230332.139"># 2D 繪圖

* 單機執行還是瀏覽器執行?
* 請畫出流程圖
* 有沒有參考資料?
</t>
<t tx="leo.20161115230332.14"># s40523146謝秉軒計算機課程

### THE HTML PRESENTATION FRAMEWORK

&lt;small&gt;
Created by [Hakim El Hattab](http://hakim.se)
[@hakimel](http://twitter.com/hakimel)
&lt;/small&gt;

[blog](blog/index.html)
    &lt;/script&gt;
&lt;/section&gt;


						
&lt;section&gt;
</t>
<t tx="leo.20161115230332.140"></t>
<t tx="leo.20161115230332.141">(uncached) yen.20161016012402.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161115230332.142">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161115230332.143">@others
</t>
<t tx="leo.20161115230332.144">(uncached) yen.20161016012402.2
Diff...
+ # 網際遊戲
+ 
+ * 單機執行還是瀏覽器執行?
+ * 請畫出流程圖
+ * 有沒有參考資料?
</t>
<t tx="leo.20161115230332.145"># 網際遊戲

* 單機執行還是瀏覽器執行?
* 請畫出流程圖
* 有沒有參考資料?
</t>
<t tx="leo.20161115230332.146"></t>
<t tx="leo.20161115230332.147">(uncached) yen.20161011143808.1
Diff...
+ &lt;section&gt;
  @others
+ &lt;/section&gt;</t>
<t tx="leo.20161115230332.148">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20161115230332.149">@others
</t>
<t tx="leo.20161115230332.15">(uncached) yen.20161016023122.1
Diff...
-     &lt;/p&gt;
-     
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
- ### 2. 熟習六種表達 
- (Six Presentation Methods, SP1-6)
- ### 3. 融入協同設計 
- (Collaborative Designs, CD1-4)
  
+ 
+ 						
</t>
<t tx="leo.20161115230332.150">(uncached) yen.20161011143808.2
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161115230332.151">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161115230332.152">@others
</t>
<t tx="leo.20161115230332.153">(uncached) yen.20161011143808.3
Diff...
+ # Github 倉儲網頁
+ 
+ ####建立個人 Github 網頁 (帳號.github.io)
+ ####建立個人課程作業網頁 (納入投影片與網誌架構)
+ ####組長建立分組的評量網頁 (納入投影片與網誌架構)
</t>
<t tx="leo.20161115230332.154"># Github 倉儲網頁

####建立個人 Github 網頁 (帳號.github.io)
####建立個人課程作業網頁 (納入投影片與網誌架構)
####組長建立分組的評量網頁 (納入投影片與網誌架構)
</t>
<t tx="leo.20161115230332.155"></t>
<t tx="leo.20161115230332.156">(uncached) yen.20161011144113.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161115230332.157">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161115230332.158">@others
</t>
<t tx="leo.20161115230332.159">(uncached) yen.20161011144113.2
Diff...
+ # 學員作業網頁定版
+ 
+ ###個人作業網頁內容可以隨時改版
+ ###分組評量網頁必須在指定時間前定版
+ ###Github 倉儲 gh-pages分支與子模組應用
</t>
<t tx="leo.20161115230332.16">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161115230332.160"># 學員作業網頁定版

###個人作業網頁內容可以隨時改版
###分組評量網頁必須在指定時間前定版
###Github 倉儲 gh-pages分支與子模組應用
</t>
<t tx="leo.20161115230332.161"></t>
<t tx="leo.20161115230332.162">(uncached) yen.20161011144715.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161115230332.163">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161115230332.164">@others
</t>
<t tx="leo.20161115230332.165">(uncached) yen.20161011144715.2
Diff...
+ # Github 倉儲拉回請求
+ 
+ ####分組倉儲 Collaborators 設定
+ ####分組倉儲版本 Pull Requests 練習
+ ####各組員實際操作影片錄製
+ ####操作影片加字幕以及影片檔相加
</t>
<t tx="leo.20161115230332.166"># Github 倉儲拉回請求

####分組倉儲 Collaborators 設定
####分組倉儲版本 Pull Requests 練習
####各組員實際操作影片錄製
####操作影片加字幕以及影片檔相加
</t>
<t tx="leo.20161115230332.167"></t>
<t tx="leo.20161115230332.168">(uncached) yen.20161011145156.1
Diff...
+ &lt;section&gt;
  @others
+ &lt;/section&gt;</t>
<t tx="leo.20161115230332.169">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20161115230332.17">    &lt;/p&gt;
    
@others
### 2. 熟習六種表達 
(Six Presentation Methods, SP1-6)
### 3. 融入協同設計 
(Collaborative Designs, CD1-4)

</t>
<t tx="leo.20161115230332.170">@others
</t>
<t tx="leo.20161115230332.171">(uncached) yen.20161011145156.2
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161115230332.172">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161115230332.173">@others
</t>
<t tx="leo.20161115230332.174">(uncached) yen.20161011145156.3
Diff...
+ # Python3 語法
+ 
+ ####print()
+ ####input()
+ ####變數名稱與關鍵字
</t>
<t tx="leo.20161115230332.175"># Python3 語法

####print()
####input()
####變數名稱與關鍵字
</t>
<t tx="leo.20161115230332.176"></t>
<t tx="leo.20161115230332.177">(uncached) yen.20161011145156.4
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161115230332.178">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161115230332.179">@others
</t>
<t tx="leo.20161115230332.18">(uncached) yen.20161016023122.2
Diff...
+ # 投影片快捷鍵
-     &lt;a href="blog/index.html"&gt;blog&lt;/a&gt;
- &lt;/section&gt;
- &lt;section&gt;
- &lt;section data-markdown&gt;
-     &lt;script type="text/template"&gt;
- # 機械設計主題教學
  
- ### 1. 強化創造能力 
- (Creative Competencies, CC1-3)
+ * 利用箭頭上下前後換頁
+ * 按 f 鍵進入全螢幕模式 (full screen)
+ * 按 s 鍵可以顯示投影片筆記 (show)
+ * 按 o 鍵可以切換單張或全域檢視 (overview)
+ * 按 b 或 . 鍵可以切換螢幕黑屏 (black)
+ * 按 Esc 可以退出全螢幕或全域檢視 (Escape)
+ 
</t>
<t tx="leo.20161115230332.180">(uncached) yen.20161011145156.5
Diff...
+ # for 迴圈用法
+ 
+ ###Python 程式縮排
+ ###for i in range(5)：
+ ###數列與 iterator
+ 
</t>
<t tx="leo.20161115230332.181"># for 迴圈用法

###Python 程式縮排
###for i in range(5)：
###數列與 iterator

</t>
<t tx="leo.20161115230332.182"></t>
<t tx="leo.20161115230332.183">(uncached) yen.20161011145156.6
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161115230332.184">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161115230332.185">@others
</t>
<t tx="leo.20161115230332.186">(uncached) yen.20161011145156.7
Diff...
+ # 函式用法
+ 
+ ####函式定義
+ ####函式呼叫與傳值
+ ####函式載入順序
</t>
<t tx="leo.20161115230332.187"># 函式用法

####函式定義
####函式呼叫與傳值
####函式載入順序
</t>
<t tx="leo.20161115230332.188"></t>
<t tx="leo.20161115230332.189">(uncached) yen.20161011145755.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161115230332.19"># 投影片快捷鍵

* 利用箭頭上下前後換頁
* 按 f 鍵進入全螢幕模式 (full screen)
* 按 s 鍵可以顯示投影片筆記 (show)
* 按 o 鍵可以切換單張或全域檢視 (overview)
* 按 b 或 . 鍵可以切換螢幕黑屏 (black)
* 按 Esc 可以退出全螢幕或全域檢視 (Escape)

</t>
<t tx="leo.20161115230332.190">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161115230332.191">@others
</t>
<t tx="leo.20161115230332.192">(uncached) yen.20161011145755.2
Diff...
+ # 數列用法
+ 
+ ####數列與索引
+ ####數列與字串
+ ####數列排序
</t>
<t tx="leo.20161115230332.193"># 數列用法

####數列與索引
####數列與字串
####數列排序
</t>
<t tx="leo.20161115230332.194"></t>
<t tx="leo.20161115230332.195">(uncached) yen.20161011145952.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161115230332.196">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161115230332.197">@others
</t>
<t tx="leo.20161115230332.198">(uncached) yen.20161011145952.2
Diff...
+ # 分組程式內容
+ 
+ ####讀取原始資料內容
+ ####設法分割資料, 納入數列
+ ####根據設計邏輯進行資料處理
</t>
<t tx="leo.20161115230332.199"># 分組程式內容

####讀取原始資料內容
####設法分割資料, 納入數列
####根據設計邏輯進行資料處理
</t>
<t tx="leo.20161115230332.2"></t>
<t tx="leo.20161115230332.20">    &lt;a href="blog/index.html"&gt;blog&lt;/a&gt;
&lt;/section&gt;
&lt;section&gt;
&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
# 機械設計主題教學

### 1. 強化創造能力 
(Creative Competencies, CC1-3)
</t>
<t tx="leo.20161115230332.200"></t>
<t tx="leo.20161115230332.201">(uncached) yen.20161011150316.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161115230332.202">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161115230332.203">@others
</t>
<t tx="leo.20161115230332.204">(uncached) yen.20161011150316.2
Diff...
+ # 遊戲邏輯
+ 
+ ####1-100 中隨機取一個數字作為答案
+ ####設法讓使用者猜這個數字 (接受輸入)
+ ####使用每猜一次都回答比答案大或小
+ ####能在一定次數中猜對者獲勝
+ ####在單機或網際執行程式?
</t>
<t tx="leo.20161115230332.205"># 遊戲邏輯

####1-100 中隨機取一個數字作為答案
####設法讓使用者猜這個數字 (接受輸入)
####使用每猜一次都回答比答案大或小
####能在一定次數中猜對者獲勝
####在單機或網際執行程式?
</t>
<t tx="leo.20161115230332.206"></t>
<t tx="leo.20161115230332.207">(uncached) yen.20161011150126.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161115230332.208">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161115230332.209">@others
</t>
<t tx="leo.20161115230332.21">(uncached) amd.20161004104820.1
Diff...
-     &lt;/script&gt;
+ &lt;section&gt;
  @others
-     &lt;/p&gt;
+ &lt;/section&gt;
</t>
<t tx="leo.20161115230332.210">(uncached) yen.20161011150126.2
Diff...
+ # Python 網際繪圖
+ 
+ ####Brython 簡介
+ ####Brython 執行設定
+ ####基本繪圖練習 (五芒星、正齒輪與各國國旗)
</t>
<t tx="leo.20161115230332.211"># Python 網際繪圖

####Brython 簡介
####Brython 執行設定
####基本繪圖練習 (五芒星、正齒輪與各國國旗)
</t>
<t tx="leo.20161115230332.212"></t>
<t tx="leo.20161115230332.213">(uncached) yen.20161011150901.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161115230332.214">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161115230332.215">@others
</t>
<t tx="leo.20161115230332.216">(uncached) yen.20161011150901.2
Diff...
+ # 網際動畫範例
+ 
+ ####機構模擬
+ ####猜顏色遊戲
+ ####網際對戰遊戲
</t>
<t tx="leo.20161115230332.217"># 網際動畫範例

####機構模擬
####猜顏色遊戲
####網際對戰遊戲
</t>
<t tx="leo.20161115230332.218"></t>
<t tx="leo.20161115230332.219">(uncached) yen.20161016012809.1
Diff...
+ &lt;section&gt;
  @others
- 
- 上述條列, 星號前有3個空白
- 
- &gt; 引言則前面加上大於的符號
- &gt; 其中也可以包含空白行
- &gt;
- &gt; 這是最後一行
-     &lt;/script&gt;
- &lt;/section&gt;
?           -
+ &lt;/section&gt;- 
- 
- 
- 						
- &lt;section data-markdown&gt;
-     &lt;script type="text/template"&gt;
- &lt;!-- 請注意, @others 不可以內縮 --&gt;
- # 影像檔案引用
- 
- and images can be specified like so:
- 
- ![Image of Yaktocat](https://octodex.github.com/images/yaktocat.png)
-     &lt;/script&gt;
- &lt;/section&gt;
- 
- 
- 
- 						
- &lt;section data-markdown&gt;
-     &lt;script type="text/template"&gt;
- &lt;!-- 請注意, @others 不可以內縮 --&gt;
- # 數學符號與方程式
- 
- Inline math equations go in like so: $\omega = d\phi / dt$. Display
- math should get its own line and be put in in double-dollarsigns:
- 
- $$I = \int \rho R^{2} dV$$
-     &lt;/script&gt;
- &lt;/section&gt;
- 
- 
- 
- 						
- &lt;section&gt;
-     &lt;h2&gt;Pretty Code&lt;/h2&gt;
-     &lt;pre&gt;
-         &lt;code class="hljs" data-trim contenteditable&gt;
-         function linkify( selector ) {
-           if( supports3DTransforms ) {
-         
-             var nodes = document.querySelectorAll( selector );
-         
-             for( var i = 0, len = nodes.length; i &amp;lt; len; i++ ) {
-               var node = nodes[i];
-         
-               if( !node.className ) {
-                 node.className += ' roll';
-               }
-             }
-           }
-         }
-         &lt;/code&gt;
-     &lt;/pre&gt;
-     &lt;p&gt;
-     Code syntax highlighting courtesy of &lt;a href="http://softwaremaniacs.org/soft/highlight/en/description/"&gt;highlight.js&lt;/a&gt;.
-     &lt;/p&gt;
- &lt;/section&gt;
- 			
- &lt;section&gt;	
-     &lt;h2&gt;Marvelous List&lt;/h2&gt;
-     &lt;ul&gt;
-     &lt;li&gt;No order here&lt;/li&gt;
-     &lt;li&gt;Or here&lt;/li&gt;
-     &lt;li&gt;Or here&lt;/li&gt;
-     &lt;li&gt;Or here&lt;/li&gt;
-     &lt;/ul&gt;
- &lt;/section&gt;
- 
- 					
- &lt;section&gt;
-     &lt;h2&gt;Fantastic Ordered List&lt;/h2&gt;
-     &lt;ol&gt;
-     &lt;li&gt;One is smaller than...&lt;/li&gt;
-     &lt;li&gt;Two is smaller than...&lt;/li&gt;
-     &lt;li&gt;Three!&lt;/li&gt;
-     &lt;/ol&gt;
- &lt;/section&gt;
- 
- 
- 					
- &lt;section&gt;
-     &lt;h2&gt;Export to PDF&lt;/h2&gt;
-     &lt;p&gt;
-     Presentations can be &lt;a href="https://github.com/hakimel/reveal.js#pdf-export"&gt;exported to PDF&lt;/a&gt;, here's an example:
-     &lt;/p&gt;	
-     &lt;iframe data-src="https://www.slideshare.net/slideshow/embed_code/42840540" width="445" height="355" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:3px solid #666; margin-bottom:5px; max-width: 100%;" allowfullscreen&gt; &lt;/iframe&gt;
- &lt;/section&gt;				
- &lt;section&gt;
- &lt;h2&gt;Global State&lt;/h2&gt;
- &lt;p&gt;
- Set &lt;code&gt;data-state="something"&lt;/code&gt; on a slide and 
- &lt;code&gt;"something"&lt;/code&gt;
- will be added as a class to the document element when the slide is open. This lets you
- apply broader style changes, like switching the page background.
- &lt;/p&gt;
- &lt;/section&gt;
- 
- 		
- &lt;section data-state="customevent"&gt;	
-     &lt;h2&gt;State Events&lt;/h2&gt;
-     &lt;p&gt;
-     Additionally custom events can be triggered on a per slide basis by binding to the &lt;code&gt;data-state&lt;/code&gt; name.
-     &lt;/p&gt;
-     &lt;pre&gt;
-         &lt;code class="javascript" data-trim contenteditable style="font-size: 18px;"&gt;
-         Reveal.addEventListener( 'customevent', function() {
-             console.log( '"customevent" has fired' );
-         } );
-         &lt;/code&gt;
-     &lt;/pre&gt;
- &lt;/section&gt;					
</t>
<t tx="leo.20161115230332.22">&lt;section&gt;
@others
&lt;/section&gt;
</t>
<t tx="leo.20161115230332.220">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20161115230332.221">@others

上述條列, 星號前有3個空白

&gt; 引言則前面加上大於的符號
&gt; 其中也可以包含空白行
&gt;
&gt; 這是最後一行
    &lt;/script&gt;
&lt;/section&gt;



						
&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
&lt;!-- 請注意, @others 不可以內縮 --&gt;
# 影像檔案引用

and images can be specified like so:

![Image of Yaktocat](https://octodex.github.com/images/yaktocat.png)
    &lt;/script&gt;
&lt;/section&gt;



						
&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
&lt;!-- 請注意, @others 不可以內縮 --&gt;
# 數學符號與方程式

Inline math equations go in like so: $\omega = d\phi / dt$. Display
math should get its own line and be put in in double-dollarsigns:

$$I = \int \rho R^{2} dV$$
    &lt;/script&gt;
&lt;/section&gt;



						
&lt;section&gt;
    &lt;h2&gt;Pretty Code&lt;/h2&gt;
    &lt;pre&gt;
        &lt;code class="hljs" data-trim contenteditable&gt;
        function linkify( selector ) {
          if( supports3DTransforms ) {
        
            var nodes = document.querySelectorAll( selector );
        
            for( var i = 0, len = nodes.length; i &amp;lt; len; i++ ) {
              var node = nodes[i];
        
              if( !node.className ) {
                node.className += ' roll';
              }
            }
          }
        }
        &lt;/code&gt;
    &lt;/pre&gt;
    &lt;p&gt;
    Code syntax highlighting courtesy of &lt;a href="http://softwaremaniacs.org/soft/highlight/en/description/"&gt;highlight.js&lt;/a&gt;.
    &lt;/p&gt;
&lt;/section&gt;
			
&lt;section&gt;	
    &lt;h2&gt;Marvelous List&lt;/h2&gt;
    &lt;ul&gt;
    &lt;li&gt;No order here&lt;/li&gt;
    &lt;li&gt;Or here&lt;/li&gt;
    &lt;li&gt;Or here&lt;/li&gt;
    &lt;li&gt;Or here&lt;/li&gt;
    &lt;/ul&gt;
&lt;/section&gt;

					
&lt;section&gt;
    &lt;h2&gt;Fantastic Ordered List&lt;/h2&gt;
    &lt;ol&gt;
    &lt;li&gt;One is smaller than...&lt;/li&gt;
    &lt;li&gt;Two is smaller than...&lt;/li&gt;
    &lt;li&gt;Three!&lt;/li&gt;
    &lt;/ol&gt;
&lt;/section&gt;


					
&lt;section&gt;
    &lt;h2&gt;Export to PDF&lt;/h2&gt;
    &lt;p&gt;
    Presentations can be &lt;a href="https://github.com/hakimel/reveal.js#pdf-export"&gt;exported to PDF&lt;/a&gt;, here's an example:
    &lt;/p&gt;	
    &lt;iframe data-src="https://www.slideshare.net/slideshow/embed_code/42840540" width="445" height="355" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:3px solid #666; margin-bottom:5px; max-width: 100%;" allowfullscreen&gt; &lt;/iframe&gt;
&lt;/section&gt;				
&lt;section&gt;
&lt;h2&gt;Global State&lt;/h2&gt;
&lt;p&gt;
Set &lt;code&gt;data-state="something"&lt;/code&gt; on a slide and 
&lt;code&gt;"something"&lt;/code&gt;
will be added as a class to the document element when the slide is open. This lets you
apply broader style changes, like switching the page background.
&lt;/p&gt;
&lt;/section&gt;

		
&lt;section data-state="customevent"&gt;	
    &lt;h2&gt;State Events&lt;/h2&gt;
    &lt;p&gt;
    Additionally custom events can be triggered on a per slide basis by binding to the &lt;code&gt;data-state&lt;/code&gt; name.
    &lt;/p&gt;
    &lt;pre&gt;
        &lt;code class="javascript" data-trim contenteditable style="font-size: 18px;"&gt;
        Reveal.addEventListener( 'customevent', function() {
            console.log( '"customevent" has fired' );
        } );
        &lt;/code&gt;
    &lt;/pre&gt;
&lt;/section&gt;					
</t>
<t tx="leo.20161115230332.222">(uncached) yen.20161016012809.2
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
+ &lt;!-- 請注意, @others 不可以內縮 --&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
  
  
  						
</t>
<t tx="leo.20161115230332.223">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
&lt;!-- 請注意, @others 不可以內縮 --&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;



						
</t>
<t tx="leo.20161115230332.224">@others


						
</t>
<t tx="leo.20161115230332.225">(uncached) yen.20161016012809.3
Diff...
+ # 數學符號與方程式
+ 
+ Inline math equations go in like so: $\omega = d\phi / dt$. Display
+ math should get its own line and be put in in double-dollarsigns:
+ 
+ $$I = \int \rho R^{2} dV$$
</t>
<t tx="leo.20161115230332.226"># 數學符號與方程式

Inline math equations go in like so: $\omega = d\phi / dt$. Display
math should get its own line and be put in in double-dollarsigns:

$$I = \int \rho R^{2} dV$$
</t>
<t tx="leo.20161115230332.227"></t>
<t tx="leo.20161115230332.228">(uncached) yen.20161016012809.6
Diff...
  &lt;section data-markdown&gt;
      &lt;script type="text/template"&gt;
  @others
- 第2段. *斜體*, **粗體**, 條列:
+     &lt;/script&gt;
+ &lt;/section&gt;
  
+ 
+ 						
-   * 第1項
-   * 第2項
-   * 第3項
</t>
<t tx="leo.20161115230332.229">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161115230332.23">    &lt;/script&gt;
@others
    &lt;/p&gt;
</t>
<t tx="leo.20161115230332.230">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
第2段. *斜體*, **粗體**, 條列:

  * 第1項
  * 第2項
  * 第3項
</t>
<t tx="leo.20161115230332.231">(uncached) yen.20161016012809.7
Diff...
+ ## 使用 iframe 導入影片
- &lt;!-- 請注意, @others 不可以內縮 --&gt;
- # h1 標題
  
- 段落用空白行隔開
+ ### 導入影片 template
  
+ &lt;iframe src="https://player.vimeo.com/video/183950627" width="640" height="492" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
</t>
<t tx="leo.20161115230332.232">## 使用 iframe 導入影片

### 導入影片 template

&lt;iframe src="https://player.vimeo.com/video/183950627" width="640" height="492" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
</t>
<t tx="leo.20161115230332.233">&lt;!-- 請注意, @others 不可以內縮 --&gt;
# h1 標題

段落用空白行隔開

</t>
<t tx="leo.20161115230332.24">(uncached) amd.20161004104641.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
+ @others
+     &lt;/script&gt;
  &lt;/section&gt;
  
- @others
- ### 1. 自學能力 (CC1, Self-learning)
- ### 2. 程式能力 (CC2, Programming)
- ### 3. 想像能力 (CC3, Imagination)
  
-     &lt;/script&gt;
+ 						
</t>
<t tx="leo.20161115230332.25">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161115230332.26">&lt;/section&gt;

@others
### 1. 自學能力 (CC1, Self-learning)
### 2. 程式能力 (CC2, Programming)
### 3. 想像能力 (CC3, Imagination)

    &lt;/script&gt;
</t>
<t tx="leo.20161115230332.27">(uncached) amd.20161004104641.2
Diff...
+ # 計算機程式在教什麼?
  
- 						
- &lt;section data-markdown&gt;
-     &lt;script type="text/template"&gt;
- # 強化創造能力
?   --  -
+ ## 創造力
? +
+ ## 表達力
+ 以及
+ ## 協同力
  
- 創造力至少包含三種元素:
</t>
<t tx="leo.20161115230332.28"># 計算機程式在教什麼?

## 創造力
## 表達力
以及
## 協同力

</t>
<t tx="leo.20161115230332.29">
						
&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
# 強化創造能力

創造力至少包含三種元素:
</t>
<t tx="leo.20161115230332.3">(uncached) amd.20161004083800.2
Diff...
  &lt;head&gt;
      &lt;meta charset="utf-8"&gt;
-     &lt;title&gt;   s40523146 謝秉軒  WELCOME
+ &lt;title&gt;    
+ 2016 Fall 計算機程式課程
  &lt;/title&gt;
      &lt;meta name="description" content="A framework for easily creating beautiful presentations using HTML"&gt;
      &lt;meta name="author" content="Hakim El Hattab"&gt;
      
      &lt;meta name="apple-mobile-web-app-capable" content="yes"&gt;
      &lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"&gt;
      
      &lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"&gt;
      
      &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/reveal.css"&gt;
      &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/theme/black.css" id="theme"&gt;
      
      &lt;!-- Theme used for syntax highlighting of code --&gt;
      &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/lib/css/zenburn.css"&gt;
  
      &lt;!-- Printing and PDF exports --&gt;
      &lt;script&gt;
          var link = document.createElement( 'link' );
          link.rel = 'stylesheet';
          link.type = 'text/css';
          link.href = window.location.search.match( /print-pdf/gi ) ? 'https://cad-lab.github.io/cadlab_data/reveal/css/print/pdf.css' : 'https://cad-lab.github.io/cadlab_data/reveal/css/print/paper.css';
          document.getElementsByTagName( 'head' )[0].appendChild( link );
      &lt;/script&gt;
  
      &lt;!--[if lt IE 9]&gt;
      &lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/html5shiv.js"&gt;&lt;/script&gt;
      &lt;![endif]--&gt;
  &lt;/head&gt;
  
</t>
<t tx="leo.20161115230332.30">(uncached) yen.20161011155543.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
+ @others
+     &lt;/script&gt;
  &lt;/section&gt;
  
+ 
+ 						
- @others
- ### 2. 文字表達 (SP2, Text Presentation)
- ### 3. 2D 表達 (SP3, 2D Presentation)
- ### 4. 3D 表達 (SP4, 3D Presentation)
- ### 5. 理論表達 (SP5, Analytical Presentation)
- ### 6. 實體表達 (SP6, Physical Presentation)
</t>
<t tx="leo.20161115230332.31">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161115230332.32">&lt;/section&gt;

@others
### 2. 文字表達 (SP2, Text Presentation)
### 3. 2D 表達 (SP3, 2D Presentation)
### 4. 3D 表達 (SP4, 3D Presentation)
### 5. 理論表達 (SP5, Analytical Presentation)
### 6. 實體表達 (SP6, Physical Presentation)
</t>
<t tx="leo.20161115230332.33">(uncached) yen.20161011155543.2
Diff...
+ # 計算機程式在教什麼?
  
- 						
- &lt;section data-markdown&gt;
-     &lt;script type="text/template"&gt;
- # 機械設計六種表達
+ ## &lt;span style="color:#FFFF00"&gt;創造力&lt;/span&gt;&lt;small&gt;=自學力+程式力+想像力&lt;/small&gt;
+ ## &lt;span style="color:#FFFF00"&gt;表達力&lt;/span&gt;&lt;small&gt;=口語+文字+2D+3D+理論+實體&lt;/small&gt;
+ &lt;span style="color:#00FF80"&gt;以及&lt;/span&gt;
+ ## &lt;span style="color:#FFFF00"&gt;協同力&lt;/span&gt;&lt;small&gt;=電腦+網路+工具+專案&lt;/small&gt;
  
- ### 1. 口語表達 (SP1, Oral Presentation)
</t>
<t tx="leo.20161115230332.34"># 計算機程式在教什麼?

## &lt;span style="color:#FFFF00"&gt;創造力&lt;/span&gt;&lt;small&gt;=自學力+程式力+想像力&lt;/small&gt;
## &lt;span style="color:#FFFF00"&gt;表達力&lt;/span&gt;&lt;small&gt;=口語+文字+2D+3D+理論+實體&lt;/small&gt;
&lt;span style="color:#00FF80"&gt;以及&lt;/span&gt;
## &lt;span style="color:#FFFF00"&gt;協同力&lt;/span&gt;&lt;small&gt;=電腦+網路+工具+專案&lt;/small&gt;

</t>
<t tx="leo.20161115230332.35">
						
&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
# 機械設計六種表達

### 1. 口語表達 (SP1, Oral Presentation)
</t>
<t tx="leo.20161115230332.36">(uncached) yen.20161011115740.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
+ @others
+     &lt;/script&gt;
+ &lt;/section&gt;
  
-     &lt;/script&gt;
- @others
- 如何融入協同產品設計?
  
+ 						
- ### 1. 了解電腦 (CD1, Computer)
- ### 2. 了解網路 (CD2, Network)
- ### 3. 了解協同設計適用之軟硬體工具 (CD3, Tools)
</t>
<t tx="leo.20161115230332.37">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161115230332.38">
    &lt;/script&gt;
@others
如何融入協同產品設計?

### 1. 了解電腦 (CD1, Computer)
### 2. 了解網路 (CD2, Network)
### 3. 了解協同設計適用之軟硬體工具 (CD3, Tools)
</t>
<t tx="leo.20161115230332.39">(uncached) yen.20161011115740.2
Diff...
- &lt;/section&gt;
+ # 計算機程式系列課程
  
+ ## 網際內容管理
+ ## 電腦輔助設計實習
+ &lt;span style="color:#00FF80"&gt;還有&lt;/span&gt;
+ ## 協同產品設計實習
+ 也在研習&lt;span style="color:#FFFF00"&gt;創造力&lt;/span&gt;、&lt;span style="color:#FFFF00"&gt;表達力&lt;/span&gt;與&lt;span style="color:#FFFF00"&gt;協同力&lt;/span&gt;
  
- 						
- &lt;section data-markdown&gt;
-     &lt;script type="text/template"&gt;
- # 融入協同設計
- 
</t>
<t tx="leo.20161115230332.4">&lt;head&gt;
    &lt;meta charset="utf-8"&gt;
&lt;title&gt;    
2016 Fall 計算機程式課程
&lt;/title&gt;
    &lt;meta name="description" content="A framework for easily creating beautiful presentations using HTML"&gt;
    &lt;meta name="author" content="Hakim El Hattab"&gt;
    
    &lt;meta name="apple-mobile-web-app-capable" content="yes"&gt;
    &lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"&gt;
    
    &lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"&gt;
    
    &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/reveal.css"&gt;
    &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/theme/black.css" id="theme"&gt;
    
    &lt;!-- Theme used for syntax highlighting of code --&gt;
    &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/lib/css/zenburn.css"&gt;

    &lt;!-- Printing and PDF exports --&gt;
    &lt;script&gt;
        var link = document.createElement( 'link' );
        link.rel = 'stylesheet';
        link.type = 'text/css';
        link.href = window.location.search.match( /print-pdf/gi ) ? 'https://cad-lab.github.io/cadlab_data/reveal/css/print/pdf.css' : 'https://cad-lab.github.io/cadlab_data/reveal/css/print/paper.css';
        document.getElementsByTagName( 'head' )[0].appendChild( link );
    &lt;/script&gt;

    &lt;!--[if lt IE 9]&gt;
    &lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/html5shiv.js"&gt;&lt;/script&gt;
    &lt;![endif]--&gt;
&lt;/head&gt;

</t>
<t tx="leo.20161115230332.40"># 計算機程式系列課程

## 網際內容管理
## 電腦輔助設計實習
&lt;span style="color:#00FF80"&gt;還有&lt;/span&gt;
## 協同產品設計實習
也在研習&lt;span style="color:#FFFF00"&gt;創造力&lt;/span&gt;、&lt;span style="color:#FFFF00"&gt;表達力&lt;/span&gt;與&lt;span style="color:#FFFF00"&gt;協同力&lt;/span&gt;

</t>
<t tx="leo.20161115230332.41">&lt;/section&gt;


						
&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
# 融入協同設計

</t>
<t tx="leo.20161115230332.42">(uncached) amd.20161004105131.1
Diff...
- ### 4. 執行協同專案 (CD4, Project)
- 
- @others
  &lt;section data-markdown&gt;
      &lt;script type="text/template"&gt;
- ## 使用 iframe 導入影片
+ @others
+     &lt;/script&gt;
+ &lt;/section&gt;
  
- ### Markdown 沒有 iframe
+ 
+ 						
</t>
<t tx="leo.20161115230332.43">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161115230332.44">### 4. 執行協同專案 (CD4, Project)

@others
&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
## 使用 iframe 導入影片

### Markdown 沒有 iframe
</t>
<t tx="leo.20161115230332.45">(uncached) amd.20161004105131.2
Diff...
+ # 何謂創造力?
  
-     &lt;/script&gt;
- &lt;/section&gt;
+ ## 能夠&lt;small&gt;&lt;span style="color:#FF0080"&gt;持續&lt;/span&gt;&lt;/small&gt;&lt;span style="color:#FFFF00"&gt;自學&lt;/span&gt;
+ ## 會安排&lt;small&gt;&lt;span style="color:#FF0080"&gt;高效&lt;/span&gt;&lt;/small&gt;&lt;span style="color:#FFFF00"&gt;可執行&lt;/span&gt;流程
+ &lt;span style="color:#00FF80"&gt;還有&lt;/span&gt;
+ ## 俱備&lt;small&gt;&lt;span style="color:#FF0080"&gt;豐富&lt;/span&gt;&lt;/small&gt;&lt;span style="color:#FFFF00"&gt;想像力&lt;/span&gt;
  
- 
- 						
- &lt;/section&gt;
</t>
<t tx="leo.20161115230332.46"># 何謂創造力?

## 能夠&lt;small&gt;&lt;span style="color:#FF0080"&gt;持續&lt;/span&gt;&lt;/small&gt;&lt;span style="color:#FFFF00"&gt;自學&lt;/span&gt;
## 會安排&lt;small&gt;&lt;span style="color:#FF0080"&gt;高效&lt;/span&gt;&lt;/small&gt;&lt;span style="color:#FFFF00"&gt;可執行&lt;/span&gt;流程
&lt;span style="color:#00FF80"&gt;還有&lt;/span&gt;
## 俱備&lt;small&gt;&lt;span style="color:#FF0080"&gt;豐富&lt;/span&gt;&lt;/small&gt;&lt;span style="color:#FFFF00"&gt;想像力&lt;/span&gt;

</t>
<t tx="leo.20161115230332.47">
    &lt;/script&gt;
&lt;/section&gt;


						
&lt;/section&gt;
</t>
<t tx="leo.20161115230332.48">(uncached) yen.20161011114704.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
+ @others
+     &lt;/script&gt;
+ &lt;/section&gt;
  
- &lt;iframe src="https://player.vimeo.com/video/191647518" width="640" height="306" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
- @others
- ## 計算機程式課程
  
+ 						
- 計算機程式課程的教學主題:
- 
-   * CC1-自學能力 (Git, Github, Python)
</t>
<t tx="leo.20161115230332.49">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161115230332.5">&lt;head&gt;
    &lt;meta charset="utf-8"&gt;
    &lt;title&gt;   s40523146 謝秉軒  WELCOME
&lt;/title&gt;
    &lt;meta name="description" content="A framework for easily creating beautiful presentations using HTML"&gt;
    &lt;meta name="author" content="Hakim El Hattab"&gt;
    
    &lt;meta name="apple-mobile-web-app-capable" content="yes"&gt;
    &lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"&gt;
    
    &lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"&gt;
    
    &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/reveal.css"&gt;
    &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/css/theme/black.css" id="theme"&gt;
    
    &lt;!-- Theme used for syntax highlighting of code --&gt;
    &lt;link rel="stylesheet" href="https://cad-lab.github.io/cadlab_data/reveal/lib/css/zenburn.css"&gt;

    &lt;!-- Printing and PDF exports --&gt;
    &lt;script&gt;
        var link = document.createElement( 'link' );
        link.rel = 'stylesheet';
        link.type = 'text/css';
        link.href = window.location.search.match( /print-pdf/gi ) ? 'https://cad-lab.github.io/cadlab_data/reveal/css/print/pdf.css' : 'https://cad-lab.github.io/cadlab_data/reveal/css/print/paper.css';
        document.getElementsByTagName( 'head' )[0].appendChild( link );
    &lt;/script&gt;

    &lt;!--[if lt IE 9]&gt;
    &lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/html5shiv.js"&gt;&lt;/script&gt;
    &lt;![endif]--&gt;
&lt;/head&gt;

</t>
<t tx="leo.20161115230332.50">
&lt;iframe src="https://player.vimeo.com/video/191647518" width="640" height="306" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
@others
## 計算機程式課程

計算機程式課程的教學主題:

  * CC1-自學能力 (Git, Github, Python)
</t>
<t tx="leo.20161115230332.51">(uncached) yen.20161011114704.2
Diff...
+ # 何謂創造力?
-     &lt;/script&gt;
- &lt;/section&gt;
  
+ ## 能夠&lt;small&gt;&lt;span style="color:#FF0080"&gt;持續&lt;/span&gt;&lt;/small&gt;自學-&gt;&lt;span style="color:#FFFF00"&gt;不一定都要別人教&lt;/span&gt;
+ ## 會安排&lt;small&gt;&lt;span style="color:#FF0080"&gt;高效&lt;/span&gt;&lt;/small&gt;可執行流程-&gt;展現&lt;span style="color:#FFFF00"&gt;執行力&lt;/span&gt;
+ &lt;span style="color:#00FF80"&gt;還有&lt;/span&gt;
+ ## 俱備&lt;small&gt;&lt;span style="color:#FF0080"&gt;豐富&lt;/span&gt;&lt;/small&gt;想像力-&gt;不受限, &lt;span style="color:#FFFF00"&gt;積極進行改造&lt;/span&gt;
  
- 						
- &lt;section data-markdown&gt;
-     &lt;script type="text/template"&gt;
</t>
<t tx="leo.20161115230332.52"># 何謂創造力?

## 能夠&lt;small&gt;&lt;span style="color:#FF0080"&gt;持續&lt;/span&gt;&lt;/small&gt;自學-&gt;&lt;span style="color:#FFFF00"&gt;不一定都要別人教&lt;/span&gt;
## 會安排&lt;small&gt;&lt;span style="color:#FF0080"&gt;高效&lt;/span&gt;&lt;/small&gt;可執行流程-&gt;展現&lt;span style="color:#FFFF00"&gt;執行力&lt;/span&gt;
&lt;span style="color:#00FF80"&gt;還有&lt;/span&gt;
## 俱備&lt;small&gt;&lt;span style="color:#FF0080"&gt;豐富&lt;/span&gt;&lt;/small&gt;想像力-&gt;不受限, &lt;span style="color:#FFFF00"&gt;積極進行改造&lt;/span&gt;

</t>
<t tx="leo.20161115230332.53">    &lt;/script&gt;
&lt;/section&gt;


						
&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
</t>
<t tx="leo.20161115230332.54">(uncached) yen.20161011121637.1
Diff...
-   * CC2-程式能力 (Python 讀檔, 排序, 2D 繪圖, 2D 動畫)
-   * SP1-口語表達 (自拍投影片 on Vimeo and Youtube)
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
  &lt;/section&gt;
  
  
  						
- &lt;section&gt;
</t>
<t tx="leo.20161115230332.55">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161115230332.56">  * CC2-程式能力 (Python 讀檔, 排序, 2D 繪圖, 2D 動畫)
  * SP1-口語表達 (自拍投影片 on Vimeo and Youtube)
@others
&lt;/section&gt;


						
&lt;section&gt;
</t>
<t tx="leo.20161115230332.57">(uncached) yen.20161011121637.2
Diff...
+ # 自學的訓練
-   * P2-文字表達 (Wiki 與 Blog on Github Pages)
-   * SP3-2D 表達 (2D 流程圖)
-   * SP4-3D 表達 (自拍操作影片 on Vimeo and Youtube)
-   * CD3-協同工具 (Git, Leo Editor 與 Github)
-   * CD4-協同專案 (網際遊戲 on Github Pages)
  
-     &lt;/script&gt;
+ ## 學員必須自己有學習動機
+ ## 能消化中英文資料
+ ## 從中體會學習的意義
+ 
+ 
</t>
<t tx="leo.20161115230332.58"># 自學的訓練

## 學員必須自己有學習動機
## 能消化中英文資料
## 從中體會學習的意義


</t>
<t tx="leo.20161115230332.59">  * P2-文字表達 (Wiki 與 Blog on Github Pages)
  * SP3-2D 表達 (2D 流程圖)
  * SP4-3D 表達 (自拍操作影片 on Vimeo and Youtube)
  * CD3-協同工具 (Git, Leo Editor 與 Github)
  * CD4-協同專案 (網際遊戲 on Github Pages)

    &lt;/script&gt;
</t>
<t tx="leo.20161115230332.6">(uncached) amd.20161004083800.5
Diff...
  &lt;body&gt;
  @others
  &lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/head.min.js"&gt;&lt;/script&gt;
  &lt;script src="https://cad-lab.github.io/cadlab_data/reveal/js/reveal.js"&gt;&lt;/script&gt;
  &lt;script&gt;
          // More info https://github.com/hakimel/reveal.js#configuration
          Reveal.initialize({
              controls: true,
              progress: true,
              history: true,
              center: true,
+ 
              transition: 'slide', // none/fade/slide/convex/concave/zoom
+ 
              // More info https://github.com/hakimel/reveal.js#dependencies
              dependencies: [
                  { src: 'https://cad-lab.github.io/cadlab_data/reveal/lib/js/classList.js', condition: function() { return !document.body.classList; } },
                  { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
                  { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
                  { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },
                  { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/zoom-js/zoom.js', async: true },
                  { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/notes/notes.js', async: true },
                  { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/math/math.js', async: true }
              ]
          });
  &lt;/script&gt;
  &lt;/body&gt;
</t>
<t tx="leo.20161115230332.60">(uncached) amd.20161004105716.1
Diff...
-     &lt;h2&gt;github_intro&lt;/h2&gt;
-     &lt;iframe src="https://player.vimeo.com/video/183950627" width="640" height="492" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
-     &lt;iframe src="https://player.vimeo.com/video/183954581" width="640" height="492" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
-     &lt;p&gt;
-     &lt;a href="https://vimeo.com/183954581"&gt;2016-09-23_fork_pull_requests&lt;/a&gt; from 
-     &lt;a href="https://vimeo.com/user24079973"&gt;虎尾科大機械設計工程&lt;/a&gt; on 
-     &lt;a href="https://vimeo.com"&gt;Vimeo&lt;/a&gt;.
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161115230332.61">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161115230332.62">    &lt;h2&gt;github_intro&lt;/h2&gt;
    &lt;iframe src="https://player.vimeo.com/video/183950627" width="640" height="492" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
@others
    &lt;iframe src="https://player.vimeo.com/video/183954581" width="640" height="492" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;p&gt;
    &lt;a href="https://vimeo.com/183954581"&gt;2016-09-23_fork_pull_requests&lt;/a&gt; from 
    &lt;a href="https://vimeo.com/user24079973"&gt;虎尾科大機械設計工程&lt;/a&gt; on 
    &lt;a href="https://vimeo.com"&gt;Vimeo&lt;/a&gt;.
</t>
<t tx="leo.20161115230332.63">(uncached) amd.20161004105716.2
Diff...
-     &lt;p&gt;
-     &lt;a href="https://vimeo.com/183950627"&gt;2016-09-23_cpb_github_intro&lt;/a&gt; from 
-     &lt;a href="https://vimeo.com/user24079973"&gt;虎尾科大機械設計工程&lt;/a&gt; on 
-     &lt;a href="https://vimeo.com"&gt;Vimeo&lt;/a&gt;.
-     &lt;/p&gt;
- &lt;/section&gt;
- &lt;section&gt;
-     &lt;h2&gt;fork_pull_requests&lt;/h2&gt;
+ # 高效執行力
+ 
+ ## 用對的方法
+ ## 在對的時機
+ ## 找對的人
+ ## 作對的事
+ 
+ 
</t>
<t tx="leo.20161115230332.64"># 高效執行力

## 用對的方法
## 在對的時機
## 找對的人
## 作對的事


</t>
<t tx="leo.20161115230332.65">    &lt;p&gt;
    &lt;a href="https://vimeo.com/183950627"&gt;2016-09-23_cpb_github_intro&lt;/a&gt; from 
    &lt;a href="https://vimeo.com/user24079973"&gt;虎尾科大機械設計工程&lt;/a&gt; on 
    &lt;a href="https://vimeo.com"&gt;Vimeo&lt;/a&gt;.
    &lt;/p&gt;
&lt;/section&gt;
&lt;section&gt;
    &lt;h2&gt;fork_pull_requests&lt;/h2&gt;
</t>
<t tx="leo.20161115230332.66">(uncached) yen.20161016004633.1
Diff...
+ &lt;section&gt;
+ @others
  &lt;/section&gt;
- @others
-     &lt;/script&gt;
</t>
<t tx="leo.20161115230332.67">&lt;section&gt;
@others
&lt;/section&gt;
</t>
<t tx="leo.20161115230332.68">&lt;/section&gt;
@others
    &lt;/script&gt;
</t>
<t tx="leo.20161115230332.69">(uncached) yen.20161016004633.4
Diff...
- &lt;!-- Example of nested vertical slides --&gt;
- &lt;section&gt;
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
- &lt;iframe src="https://player.vimeo.com/video/183950627" width="640" height="492" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
      &lt;/script&gt;
  &lt;/section&gt;
  
  
+ 						
</t>
<t tx="leo.20161115230332.7">&lt;body&gt;
@others
&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/js/reveal.js"&gt;&lt;/script&gt;
&lt;script&gt;
        // More info https://github.com/hakimel/reveal.js#configuration
        Reveal.initialize({
            controls: true,
            progress: true,
            history: true,
            center: true,

            transition: 'slide', // none/fade/slide/convex/concave/zoom

            // More info https://github.com/hakimel/reveal.js#dependencies
            dependencies: [
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/lib/js/classList.js', condition: function() { return !document.body.classList; } },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/zoom-js/zoom.js', async: true },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/notes/notes.js', async: true },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/math/math.js', async: true }
            ]
        });
&lt;/script&gt;
&lt;/body&gt;
</t>
<t tx="leo.20161115230332.70">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161115230332.71">&lt;!-- Example of nested vertical slides --&gt;
&lt;section&gt;
@others
&lt;iframe src="https://player.vimeo.com/video/183950627" width="640" height="492" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;/script&gt;
&lt;/section&gt;


</t>
<t tx="leo.20161115230332.72">(uncached) yen.20161016004633.5
Diff...
+ # 計算機程式課程規劃
- &lt;section data-markdown&gt;
-     &lt;script type="text/template"&gt;
- ## 使用 iframe 導入影片
  
- ### Markdown 沒有 iframe
+ ## [課程規劃](https://github.com/mdecourse/2016fallcp/blob/master/syllabus.py)
+ ## [課程 Wiki](https://github.com/mdecourse/2016fallcp/wiki)
+ ## [課程網誌](http://chiamingyen.github.io/kmolab/blog/tag/2016fallcp.html)
  
</t>
<t tx="leo.20161115230332.73"># 計算機程式課程規劃

## [課程規劃](https://github.com/mdecourse/2016fallcp/blob/master/syllabus.py)
## [課程 Wiki](https://github.com/mdecourse/2016fallcp/wiki)
## [課程網誌](http://chiamingyen.github.io/kmolab/blog/tag/2016fallcp.html)

</t>
<t tx="leo.20161115230332.74">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
## 使用 iframe 導入影片

### Markdown 沒有 iframe

</t>
<t tx="leo.20161115230332.75">(uncached) yen.20161016010643.1
Diff...
- 						
- &lt;section&gt;
- @others
-     &lt;/a&gt;
- &lt;/section&gt;
- &lt;/section&gt;
  &lt;section data-markdown&gt;
      &lt;script type="text/template"&gt;
+ @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161115230332.76">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161115230332.77">						
&lt;section&gt;
@others
    &lt;/a&gt;
&lt;/section&gt;
&lt;/section&gt;
&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
</t>
<t tx="leo.20161115230332.78">(uncached) yen.20161016010643.2
Diff...
-     &lt;h2&gt;Vertical Slides&lt;/h2&gt;
-     &lt;p&gt;Slides can be nested inside of each other.&lt;/p&gt;
-     &lt;p&gt;
-     Use the &lt;em&gt;Space&lt;/em&gt; key to navigate through all slides.
-     &lt;/p&gt;
-     &lt;br&gt;
-     &lt;a href="#" class="navigate-down"&gt;
-         &lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
+ ## 下載 miniconda 可攜環境
+ 
+   * 在電腦教室下載 [mini2016fall.7z](http://140.130.17.17/public/2016fall/mini2016fall_with_leo.7z)
+   * 從外部下載 [mini2016fall.7z](https://140.130.17.101/download/?filepath=/home/yen/cmsimply/wsgi/local_data/downloads/mini2016fall_with_leo.7z)
+   * start.bat 啟動, stop.bat 關閉
+   * 建議存在隨身硬碟中使用
+ 
+ 
</t>
<t tx="leo.20161115230332.79">## 下載 miniconda 可攜環境

  * 在電腦教室下載 [mini2016fall.7z](http://140.130.17.17/public/2016fall/mini2016fall_with_leo.7z)
  * 從外部下載 [mini2016fall.7z](https://140.130.17.101/download/?filepath=/home/yen/cmsimply/wsgi/local_data/downloads/mini2016fall_with_leo.7z)
  * start.bat 啟動, stop.bat 關閉
  * 建議存在隨身硬碟中使用


</t>
<t tx="leo.20161115230332.8">&lt;body&gt;
@others
&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="https://cad-lab.github.io/cadlab_data/reveal/js/reveal.js"&gt;&lt;/script&gt;
&lt;script&gt;
        // More info https://github.com/hakimel/reveal.js#configuration
        Reveal.initialize({
            controls: true,
            progress: true,
            history: true,
            center: true,
            transition: 'slide', // none/fade/slide/convex/concave/zoom
            // More info https://github.com/hakimel/reveal.js#dependencies
            dependencies: [
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/lib/js/classList.js', condition: function() { return !document.body.classList; } },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/zoom-js/zoom.js', async: true },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/notes/notes.js', async: true },
                { src: 'https://cad-lab.github.io/cadlab_data/reveal/plugin/math/math.js', async: true }
            ]
        });
&lt;/script&gt;
&lt;/body&gt;
</t>
<t tx="leo.20161115230332.80">    &lt;h2&gt;Vertical Slides&lt;/h2&gt;
    &lt;p&gt;Slides can be nested inside of each other.&lt;/p&gt;
    &lt;p&gt;
    Use the &lt;em&gt;Space&lt;/em&gt; key to navigate through all slides.
    &lt;/p&gt;
    &lt;br&gt;
    &lt;a href="#" class="navigate-down"&gt;
        &lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
</t>
<t tx="leo.20161115230332.81">(uncached) yen.20161016010719.1
Diff...
- ## Markdown support
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
+ @others
+     &lt;/script&gt;
+ &lt;/section&gt;
  
- @others
  
+ 						
-   Write content using inline or external Markdown.
-   Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
- &lt;/section&gt;
- ```
</t>
<t tx="leo.20161115230332.82">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161115230332.83">## Markdown support

@others

  Write content using inline or external Markdown.
  Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
&lt;/section&gt;
```
</t>
<t tx="leo.20161115230332.84">(uncached) yen.20161016012922.1
Diff...
+ ## 學員自評項目
- Write content using inline or external Markdown.
- Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
  
- ```
- &lt;section data-markdown&gt;
-   ## Markdown support
+ * 上課筆記與心得寫在個人的 2016fallcp_hw 倉儲 Wiki 中
+ * 利用 [ShareX](https://getsharex.com/) 錄製上課操作練習影片
+ * 將影片加上說明字幕後, 上傳至個人 [Vimeo](https://vimeo.com/) 與 [Youtube](https://www.youtube.com)
+ * 每週更新個人與分組的 Github Pages 投影片與網誌</t>
<t tx="leo.20161115230332.85">## 學員自評項目

* 上課筆記與心得寫在個人的 2016fallcp_hw 倉儲 Wiki 中
* 利用 [ShareX](https://getsharex.com/) 錄製上課操作練習影片
* 將影片加上說明字幕後, 上傳至個人 [Vimeo](https://vimeo.com/) 與 [Youtube](https://www.youtube.com)
* 每週更新個人與分組的 Github Pages 投影片與網誌</t>
<t tx="leo.20161115230332.86">Write content using inline or external Markdown.
Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).

```
&lt;section data-markdown&gt;
  ## Markdown support
</t>
<t tx="leo.20161115230332.87">(uncached) yen.20161011122932.1
Diff...
- &lt;/section&gt;
?  -
+ &lt;section&gt;
  @others
+ &lt;/section&gt;</t>
<t tx="leo.20161115230332.88">&lt;section&gt;
@others
&lt;/section&gt;</t>
<t tx="leo.20161115230332.89">&lt;/section&gt;
@others
</t>
<t tx="leo.20161115230332.9">(uncached) amd.20161004095719.1
Diff...
  &lt;section data-markdown&gt;
      &lt;script type="text/template"&gt;
  @others
-     &lt;h1&gt;s40523146  謝秉軒  Welcome&lt;/h1&gt;
-     &lt;p&gt;
-     &lt;small&gt;
-     Created by &lt;a href="http://chiamingyen.github.io/kmolab/blog/tag/2016fallcp.html"&gt;s40523142&lt;/a&gt;
-     &lt;/small&gt;
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161115230332.90">(uncached) yen.20161011122601.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161115230332.91">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161115230332.92">@others
</t>
<t tx="leo.20161115230332.93">(uncached) yen.20161011122601.2
Diff...
+ # 自學 Python3
+ 
+ [Python3 程式範例](https://github.com/mdecourse/2016fallcp/blob/master/python3program.py)
+ ### 在哪裡執行?
+ ### 如何執行?
+ ### 如何寫心得?
+ ### 如何錄製操作過程?
</t>
<t tx="leo.20161115230332.94"># 自學 Python3

[Python3 程式範例](https://github.com/mdecourse/2016fallcp/blob/master/python3program.py)
### 在哪裡執行?
### 如何執行?
### 如何寫心得?
### 如何錄製操作過程?
</t>
<t tx="leo.20161115230332.95"></t>
<t tx="leo.20161115230332.96">(uncached) yen.20161011122957.1
Diff...
+ &lt;section data-markdown&gt;
+     &lt;script type="text/template"&gt;
  @others
+     &lt;/script&gt;
+ &lt;/section&gt;
+ 
+ 
+ 						
</t>
<t tx="leo.20161115230332.97">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;


						
</t>
<t tx="leo.20161115230332.98">@others
</t>
<t tx="leo.20161115230332.99">(uncached) yen.20161011122957.2
Diff...
+ # 在哪裡執行?
+ 
+ ### 單機操作系統中 (近端)
+ ### 單機連結到遠端主機中 (遠端)
+ ### 瀏覽器中 (網際端)
</t>
<t tx="leo.20161118133515.10">### 4. 執行協同專案 (CD4, Project)

@others
&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
## 使用 iframe 導入影片

### Markdown 沒有 iframe
</t>
<t tx="leo.20161118133515.11">### 4. 執行協同專案 (CD4, Project)

@others
&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
## GIT CLONE

</t>
<t tx="leo.20161118133515.12">(uncached) yen.20161011114704.2
Diff...
      &lt;/script&gt;
  &lt;/section&gt;
  
- 	
- 	
  
- &lt;section data-markdown&gt;
-     &lt;script type="text/template"&gt;
- ## GIT BRANCH &amp; GIT CHECK OUT
- 
- &lt;iframe src="https://player.vimeo.com/video/191647519" width="640" height="306" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
-     &lt;/script&gt;
- &lt;/section&gt;
- 	
- 	
- 	
- 	
  						
  &lt;section data-markdown&gt;
      &lt;script type="text/template"&gt;
</t>
<t tx="leo.20161118133515.13">    &lt;/script&gt;
&lt;/section&gt;


						
&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
</t>
<t tx="leo.20161118133515.14">    &lt;/script&gt;
&lt;/section&gt;

	
	

&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
## GIT BRANCH &amp; GIT CHECK OUT

&lt;iframe src="https://player.vimeo.com/video/191647519" width="640" height="306" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;/script&gt;
&lt;/section&gt;
	
	
	
	
						
&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
</t>
<t tx="leo.20161118133515.2"></t>
<t tx="leo.20161118133515.3">(uncached) amd.20161004095719.1
Diff...
  &lt;section data-markdown&gt;
      &lt;script type="text/template"&gt;
  @others
      &lt;h1&gt;s40523146  謝秉軒  Welcome&lt;/h1&gt;
      &lt;p&gt;
      &lt;small&gt;
-     Created by &lt;a href="https://github.com/s40523146"&gt;s40523146&lt;/a&gt;
+     Created by &lt;a href="http://chiamingyen.github.io/kmolab/blog/tag/2016fallcp.html"&gt;s40523142&lt;/a&gt;
      &lt;/small&gt;
</t>
<t tx="leo.20161118133515.4">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;h1&gt;s40523146  謝秉軒  Welcome&lt;/h1&gt;
    &lt;p&gt;
    &lt;small&gt;
    Created by &lt;a href="http://chiamingyen.github.io/kmolab/blog/tag/2016fallcp.html"&gt;s40523142&lt;/a&gt;
    &lt;/small&gt;
</t>
<t tx="leo.20161118133515.5">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
    &lt;h1&gt;s40523146  謝秉軒  Welcome&lt;/h1&gt;
    &lt;p&gt;
    &lt;small&gt;
    Created by &lt;a href="https://github.com/s40523146"&gt;s40523146&lt;/a&gt;
    &lt;/small&gt;
</t>
<t tx="leo.20161118133515.6">(uncached) amd.20161004095719.2
Diff...
  # s40523146謝秉軒計算機課程
  
  ### THE HTML PRESENTATION FRAMEWORK
  
  &lt;small&gt;
- Created by s40523146
- [s40523146](https://github.com/s40523146)
+ Created by [Hakim El Hattab](http://hakim.se)
+ [@hakimel](http://twitter.com/hakimel)
  &lt;/small&gt;
  
  [blog](blog/index.html)
      &lt;/script&gt;
  &lt;/section&gt;
  
  
  						
  &lt;section&gt;
</t>
<t tx="leo.20161118133515.7"># s40523146謝秉軒計算機課程

### THE HTML PRESENTATION FRAMEWORK

&lt;small&gt;
Created by [Hakim El Hattab](http://hakim.se)
[@hakimel](http://twitter.com/hakimel)
&lt;/small&gt;

[blog](blog/index.html)
    &lt;/script&gt;
&lt;/section&gt;


						
&lt;section&gt;
</t>
<t tx="leo.20161118133515.8"># s40523146謝秉軒計算機課程

### THE HTML PRESENTATION FRAMEWORK

&lt;small&gt;
Created by s40523146
[s40523146](https://github.com/s40523146)
&lt;/small&gt;

[blog](blog/index.html)
    &lt;/script&gt;
&lt;/section&gt;


						
&lt;section&gt;
</t>
<t tx="leo.20161118133515.9">(uncached) amd.20161004105131.1
Diff...
  ### 4. 執行協同專案 (CD4, Project)
  
  @others
  &lt;section data-markdown&gt;
      &lt;script type="text/template"&gt;
- ## GIT CLONE
+ ## 使用 iframe 導入影片
  
+ ### Markdown 沒有 iframe
</t>
<t tx="yen.20161011114704.1">
&lt;iframe src="https://player.vimeo.com/video/191647518" width="640" height="306" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
@others
## 計算機程式課程

計算機程式課程的教學主題:

  * CC1-自學能力 (Git, Github, Python)
</t>
<t tx="yen.20161011114704.2">    &lt;/script&gt;
&lt;/section&gt;

	
	

&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
## GIT BRANCH &amp; GIT CHECK OUT

&lt;iframe src="https://player.vimeo.com/video/191647519" width="640" height="306" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;/script&gt;
&lt;/section&gt;
	
	
	
	
						
&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
</t>
<t tx="yen.20161011115740.1">
    &lt;/script&gt;
@others
如何融入協同產品設計?

### 1. 了解電腦 (CD1, Computer)
### 2. 了解網路 (CD2, Network)
### 3. 了解協同設計適用之軟硬體工具 (CD3, Tools)
</t>
<t tx="yen.20161011115740.2">&lt;/section&gt;


						
&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
# 融入協同設計

</t>
<t tx="yen.20161011121637.1">  * CC2-程式能力 (Python 讀檔, 排序, 2D 繪圖, 2D 動畫)
  * SP1-口語表達 (自拍投影片 on Vimeo and Youtube)
@others
&lt;/section&gt;


						
&lt;section&gt;
</t>
<t tx="yen.20161011121637.2">  * P2-文字表達 (Wiki 與 Blog on Github Pages)
  * SP3-2D 表達 (2D 流程圖)
  * SP4-3D 表達 (自拍操作影片 on Vimeo and Youtube)
  * CD3-協同工具 (Git, Leo Editor 與 Github)
  * CD4-協同專案 (網際遊戲 on Github Pages)

    &lt;/script&gt;
</t>
<t tx="yen.20161011122601.1">@others
</t>
<t tx="yen.20161011122601.2"></t>
<t tx="yen.20161011122932.1">&lt;/section&gt;
@others
</t>
<t tx="yen.20161011122957.1">@others
</t>
<t tx="yen.20161011122957.2"></t>
<t tx="yen.20161011123951.1">@others
</t>
<t tx="yen.20161011123951.2"></t>
<t tx="yen.20161011124118.1">@others
</t>
<t tx="yen.20161011124118.2"></t>
<t tx="yen.20161011125115.1">@others
</t>
<t tx="yen.20161011125115.2">@others
</t>
<t tx="yen.20161011125115.3"></t>
<t tx="yen.20161011143808.1">@others
</t>
<t tx="yen.20161011143808.2">@others
</t>
<t tx="yen.20161011143808.3"></t>
<t tx="yen.20161011144113.1">@others
</t>
<t tx="yen.20161011144113.2"></t>
<t tx="yen.20161011144715.1">@others
</t>
<t tx="yen.20161011144715.2"></t>
<t tx="yen.20161011145156.1">@others
</t>
<t tx="yen.20161011145156.2">@others
</t>
<t tx="yen.20161011145156.3"></t>
<t tx="yen.20161011145156.4">@others
</t>
<t tx="yen.20161011145156.5"></t>
<t tx="yen.20161011145156.6">@others
</t>
<t tx="yen.20161011145156.7"></t>
<t tx="yen.20161011145755.1">@others
</t>
<t tx="yen.20161011145755.2"></t>
<t tx="yen.20161011145952.1">@others
</t>
<t tx="yen.20161011145952.2"></t>
<t tx="yen.20161011150126.1">@others
</t>
<t tx="yen.20161011150126.2"></t>
<t tx="yen.20161011150316.1">@others
</t>
<t tx="yen.20161011150316.2"></t>
<t tx="yen.20161011150901.1">@others
</t>
<t tx="yen.20161011150901.2"></t>
<t tx="yen.20161011155543.1">&lt;/section&gt;

@others
### 2. 文字表達 (SP2, Text Presentation)
### 3. 2D 表達 (SP3, 2D Presentation)
### 4. 3D 表達 (SP4, 3D Presentation)
### 5. 理論表達 (SP5, Analytical Presentation)
### 6. 實體表達 (SP6, Physical Presentation)
</t>
<t tx="yen.20161011155543.2">
						
&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
# 機械設計六種表達

### 1. 口語表達 (SP1, Oral Presentation)
</t>
<t tx="yen.20161016004633.1">&lt;/section&gt;
@others
    &lt;/script&gt;
</t>
<t tx="yen.20161016004633.4">&lt;!-- Example of nested vertical slides --&gt;
&lt;section&gt;
@others
&lt;iframe src="https://player.vimeo.com/video/183950627" width="640" height="492" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt;
    &lt;/script&gt;
&lt;/section&gt;


</t>
<t tx="yen.20161016004633.5">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
## 使用 iframe 導入影片

### Markdown 沒有 iframe

</t>
<t tx="yen.20161016010643.1">						
&lt;section&gt;
@others
    &lt;/a&gt;
&lt;/section&gt;
&lt;/section&gt;
&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
</t>
<t tx="yen.20161016010643.2">    &lt;h2&gt;Vertical Slides&lt;/h2&gt;
    &lt;p&gt;Slides can be nested inside of each other.&lt;/p&gt;
    &lt;p&gt;
    Use the &lt;em&gt;Space&lt;/em&gt; key to navigate through all slides.
    &lt;/p&gt;
    &lt;br&gt;
    &lt;a href="#" class="navigate-down"&gt;
        &lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
</t>
<t tx="yen.20161016010719.1">## Markdown support

@others

  Write content using inline or external Markdown.
  Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
&lt;/section&gt;
```
</t>
<t tx="yen.20161016011920.1">@others
</t>
<t tx="yen.20161016011920.2"></t>
<t tx="yen.20161016012215.1">@others
</t>
<t tx="yen.20161016012215.2"></t>
<t tx="yen.20161016012253.1">@others
</t>
<t tx="yen.20161016012253.2"></t>
<t tx="yen.20161016012402.1">@others
</t>
<t tx="yen.20161016012402.2"></t>
<t tx="yen.20161016012809.1">@others

上述條列, 星號前有3個空白

&gt; 引言則前面加上大於的符號
&gt; 其中也可以包含空白行
&gt;
&gt; 這是最後一行
    &lt;/script&gt;
&lt;/section&gt;



						
&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
&lt;!-- 請注意, @others 不可以內縮 --&gt;
# 影像檔案引用

and images can be specified like so:

![Image of Yaktocat](https://octodex.github.com/images/yaktocat.png)
    &lt;/script&gt;
&lt;/section&gt;



						
&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
&lt;!-- 請注意, @others 不可以內縮 --&gt;
# 數學符號與方程式

Inline math equations go in like so: $\omega = d\phi / dt$. Display
math should get its own line and be put in in double-dollarsigns:

$$I = \int \rho R^{2} dV$$
    &lt;/script&gt;
&lt;/section&gt;



						
&lt;section&gt;
    &lt;h2&gt;Pretty Code&lt;/h2&gt;
    &lt;pre&gt;
        &lt;code class="hljs" data-trim contenteditable&gt;
        function linkify( selector ) {
          if( supports3DTransforms ) {
        
            var nodes = document.querySelectorAll( selector );
        
            for( var i = 0, len = nodes.length; i &amp;lt; len; i++ ) {
              var node = nodes[i];
        
              if( !node.className ) {
                node.className += ' roll';
              }
            }
          }
        }
        &lt;/code&gt;
    &lt;/pre&gt;
    &lt;p&gt;
    Code syntax highlighting courtesy of &lt;a href="http://softwaremaniacs.org/soft/highlight/en/description/"&gt;highlight.js&lt;/a&gt;.
    &lt;/p&gt;
&lt;/section&gt;
			
&lt;section&gt;	
    &lt;h2&gt;Marvelous List&lt;/h2&gt;
    &lt;ul&gt;
    &lt;li&gt;No order here&lt;/li&gt;
    &lt;li&gt;Or here&lt;/li&gt;
    &lt;li&gt;Or here&lt;/li&gt;
    &lt;li&gt;Or here&lt;/li&gt;
    &lt;/ul&gt;
&lt;/section&gt;

					
&lt;section&gt;
    &lt;h2&gt;Fantastic Ordered List&lt;/h2&gt;
    &lt;ol&gt;
    &lt;li&gt;One is smaller than...&lt;/li&gt;
    &lt;li&gt;Two is smaller than...&lt;/li&gt;
    &lt;li&gt;Three!&lt;/li&gt;
    &lt;/ol&gt;
&lt;/section&gt;


					
&lt;section&gt;
    &lt;h2&gt;Export to PDF&lt;/h2&gt;
    &lt;p&gt;
    Presentations can be &lt;a href="https://github.com/hakimel/reveal.js#pdf-export"&gt;exported to PDF&lt;/a&gt;, here's an example:
    &lt;/p&gt;	
    &lt;iframe data-src="https://www.slideshare.net/slideshow/embed_code/42840540" width="445" height="355" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:3px solid #666; margin-bottom:5px; max-width: 100%;" allowfullscreen&gt; &lt;/iframe&gt;
&lt;/section&gt;				
&lt;section&gt;
&lt;h2&gt;Global State&lt;/h2&gt;
&lt;p&gt;
Set &lt;code&gt;data-state="something"&lt;/code&gt; on a slide and 
&lt;code&gt;"something"&lt;/code&gt;
will be added as a class to the document element when the slide is open. This lets you
apply broader style changes, like switching the page background.
&lt;/p&gt;
&lt;/section&gt;

		
&lt;section data-state="customevent"&gt;	
    &lt;h2&gt;State Events&lt;/h2&gt;
    &lt;p&gt;
    Additionally custom events can be triggered on a per slide basis by binding to the &lt;code&gt;data-state&lt;/code&gt; name.
    &lt;/p&gt;
    &lt;pre&gt;
        &lt;code class="javascript" data-trim contenteditable style="font-size: 18px;"&gt;
        Reveal.addEventListener( 'customevent', function() {
            console.log( '"customevent" has fired' );
        } );
        &lt;/code&gt;
    &lt;/pre&gt;
&lt;/section&gt;					
</t>
<t tx="yen.20161016012809.2">@others


						
</t>
<t tx="yen.20161016012809.3"></t>
<t tx="yen.20161016012809.4">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
&lt;!-- 請注意, @others 不可以內縮 --&gt;
@others
    &lt;/script&gt;
&lt;/section&gt;



						
</t>
<t tx="yen.20161016012809.5">## 利用 Markdown 寫投影片
以下利用 Markdown 格式展示 Python 程式碼:
```
@language python
# use threading and subprocess to threading the make process
import os
import subprocess
import threading

def domake():
    
    path = "../exposed/api/exposed"
    ubuntu = "../Ubuntu"
    
    # create obj path
    
    if not os.path.exists(path+"/../obj"):
        os.makedirs(path+"/../obj")
    
    subprocess.call(["make", "clean"], cwd=path)
    subprocess.call("make", cwd=path)
    subprocess.call(["cp", "{libslvs.so, _slvs.so, slvs.py}", ubuntu], cwd=path)
    subprocess.call(["python3", "circle_ex.py"], cwd=path+"/"+ubuntu)
    
make = threading.Thread(target=domake)
make.start()
```
</t>
<t tx="yen.20161016012809.6">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
@others
第2段. *斜體*, **粗體**, 條列:

  * 第1項
  * 第2項
  * 第3項
</t>
<t tx="yen.20161016012809.7">&lt;!-- 請注意, @others 不可以內縮 --&gt;
# h1 標題

段落用空白行隔開

</t>
<t tx="yen.20161016012922.1">Write content using inline or external Markdown.
Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).

```
&lt;section data-markdown&gt;
  ## Markdown support
</t>
<t tx="yen.20161016023122.1">    &lt;/p&gt;
    
@others
### 2. 熟習六種表達 
(Six Presentation Methods, SP1-6)
### 3. 融入協同設計 
(Collaborative Designs, CD1-4)

</t>
<t tx="yen.20161016023122.2">    &lt;a href="blog/index.html"&gt;blog&lt;/a&gt;
&lt;/section&gt;
&lt;section&gt;
&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
# 機械設計主題教學

### 1. 強化創造能力 
(Creative Competencies, CC1-3)
</t>
<t tx="yen.20161022111056.1">@language python
import os
import subprocess
import threading
import http.server, ssl

def domake():
    # build directory
    os.chdir("./../")
    server_address = ('localhost', 5443)
    httpd = http.server.HTTPServer(server_address, http.server.SimpleHTTPRequestHandler)
    httpd.socket = ssl.wrap_socket(httpd.socket,
                                   server_side=True,
                                   certfile='localhost.crt',
                                   keyfile='localhost.key',
                                   ssl_version=ssl.PROTOCOL_TLSv1)
    print("5443 https server started")
    httpd.serve_forever()

# 利用執行緒執行 https 伺服器
make = threading.Thread(target=domake)
make.start()</t>
<t tx="yen.20161022151749.1">sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout localhost.key -out localhost.crt

</t>
</tnodes>
</leo_file>
